// Copyright IBM Corp. 2014, 2026
// Copyright 2026 Google LLC
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This code is generated by Magic Modules using the following:
//
//     Configuration: https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/products/networkservices/RegionalMulticastGroupConsumerActivation.yaml
//     Template:      https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/resource.go.tmpl
//
//     DO NOT EDIT this file directly. Any changes made to this file will be
//     overwritten during the next generation cycle.
//
// ----------------------------------------------------------------------------

package networkservices

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"reflect"
	"regexp"
	"slices"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/hashicorp/errwrap"
	"github.com/hashicorp/go-cty/cty"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/customdiff"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/id"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/logging"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/retry"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/structure"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	"github.com/hashicorp/terraform-plugin-sdk/v2/terraform"
	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/registry"
	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/tpgresource"
	transport_tpg "github.com/hashicorp/terraform-provider-google-nightly/google-nightly/transport"
	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/verify"

	"google.golang.org/api/googleapi"
)

var (
	_ = bytes.Clone
	_ = context.WithCancel
	_ = base64.NewDecoder
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = log.Print
	_ = http.Get
	_ = reflect.ValueOf
	_ = regexp.Match
	_ = slices.Min([]int{1})
	_ = sort.IntSlice{}
	_ = strconv.Atoi
	_ = strings.Trim
	_ = time.Now
	_ = errwrap.Wrap
	_ = cty.BoolVal
	_ = diag.Diagnostic{}
	_ = customdiff.All
	_ = id.UniqueId
	_ = logging.LogLevel
	_ = retry.Retry
	_ = schema.Noop
	_ = validation.All
	_ = structure.ExpandJsonFromString
	_ = terraform.State{}
	_ = tpgresource.SetLabels
	_ = transport_tpg.Config{}
	_ = verify.ValidateEnum
	_ = googleapi.Error{}
)

func init() {
	registry.Schema{
		Name:        "google_network_services_regional_multicast_group_consumer_activation",
		ProductName: "networkservices",
		Type:        registry.SchemaTypeResource,
		Schema:      ResourceNetworkServicesRegionalMulticastGroupConsumerActivation(),
	}.Register()
}

func ResourceNetworkServicesRegionalMulticastGroupConsumerActivation() *schema.Resource {
	return &schema.Resource{
		Create: resourceNetworkServicesRegionalMulticastGroupConsumerActivationCreate,
		Read:   resourceNetworkServicesRegionalMulticastGroupConsumerActivationRead,
		Update: resourceNetworkServicesRegionalMulticastGroupConsumerActivationUpdate,
		Delete: resourceNetworkServicesRegionalMulticastGroupConsumerActivationDelete,

		Importer: &schema.ResourceImporter{
			State: resourceNetworkServicesRegionalMulticastGroupConsumerActivationImport,
		},

		Timeouts: &schema.ResourceTimeout{
			Create: schema.DefaultTimeout(20 * time.Minute),
			Update: schema.DefaultTimeout(20 * time.Minute),
			Delete: schema.DefaultTimeout(20 * time.Minute),
		},

		CustomizeDiff: customdiff.All(
			tpgresource.SetLabelsDiff,
			tpgresource.DefaultProviderProject,
			tpgresource.DefaultProviderDeletionPolicy("DELETE"),
		),

		Identity: &schema.ResourceIdentity{
			Version: 1,
			SchemaFunc: func() map[string]*schema.Schema {
				return map[string]*schema.Schema{
					"location": {
						Type:              schema.TypeString,
						RequiredForImport: true,
					},
					"regional_multicast_group_consumer_activation_id": {
						Type:              schema.TypeString,
						RequiredForImport: true,
					},
					"project": {
						Type:              schema.TypeString,
						OptionalForImport: true,
					},
				}
			},
		},
		ResourceBehavior: schema.ResourceBehavior{
			MutableIdentity: true,
		},

		Schema: map[string]*schema.Schema{
			"interconnect_attachments": {
				Type:     schema.TypeList,
				Required: true,
				Description: `The resource name of the interconnect attachments that are in the same
region as this regional multicast group consumer activation and are used by
on-premises consumers to receive multicast traffic.
These attachments must have multicast functionality enabled.
Use the following format: 'projects/*/regions/*/interconnectAttachments/*'.`,
				Elem: &schema.Schema{
					Type: schema.TypeString,
				},
			},
			"location": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: `Resource ID segment making up resource 'name'. It identifies the resource within its parent collection as described in https://google.aip.dev/122.`,
			},
			"regional_multicast_consumer_association": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
				Description: `The resource name of the regional multicast consumer association that is in
the same region as this regional multicast group consumer activation.
Use the following format:
'projects/*/locations/*/regionalMulticastConsumerAssociations/*'.`,
			},
			"regional_multicast_group_consumer_activation_id": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
				Description: `A unique name for the regional multicast group consumer activation.
The name is restricted to lower-case letters, numbers, and hyphen, with
the first character a lower-case letter, and the last a letter or a
number. The name must not exceed 63 characters.`,
			},
			"regional_multicast_group_range_activation": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
				Description: `The resource name of the regional multicast group range activation created
by the admin in the same region as this regional multicast group consumer
activation.
Use the following format:
'projects/*/locations/*/regionalMulticastGroupRangeActivations/*'.`,
			},
			"description": {
				Type:     schema.TypeString,
				Optional: true,
				Description: `An optional text description of the regional multicast group consumer
activation.`,
			},
			"labels": {
				Type:     schema.TypeMap,
				Optional: true,
				Description: `Labels as key-value pairs

**Note**: This field is non-authoritative, and will only manage the labels present in your configuration.
Please refer to the field 'effective_labels' for all of the labels present on the resource.`,
				Elem: &schema.Schema{Type: schema.TypeString},
			},
			"log_config": {
				Type:        schema.TypeList,
				Optional:    true,
				Description: `The logging configuration.`,
				MaxItems:    1,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"enabled": {
							Type:        schema.TypeBool,
							Optional:    true,
							Description: `Whether to enable logging or not.`,
						},
					},
				},
			},
			"create_time": {
				Type:     schema.TypeString,
				Computed: true,
				Description: `[Output only] The timestamp when the regional multicast group consumer
activation was created.`,
			},
			"effective_labels": {
				Type:        schema.TypeMap,
				Computed:    true,
				Description: `All of labels (key/value pairs) present on the resource in GCP, including the labels configured through Terraform, other clients and services.`,
				Elem:        &schema.Schema{Type: schema.TypeString},
			},
			"name": {
				Type:     schema.TypeString,
				Computed: true,
				Description: `Identifier. The resource name of the regional multicast group consumer activation.
Use the following format:
'projects/*/locations/*/regionalMulticastGroupConsumerActivations/*'.`,
			},
			"state": {
				Type:        schema.TypeList,
				Computed:    true,
				Description: `The multicast resource's state.`,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"state": {
							Type:     schema.TypeString,
							Computed: true,
							Description: `The state of the multicast resource.
Possible values:
CREATING
ACTIVE
DELETING
DELETE_FAILED
UPDATING
UPDATE_FAILED
INACTIVE
OBSOLETE`,
						},
					},
				},
			},
			"terraform_labels": {
				Type:     schema.TypeMap,
				Computed: true,
				Description: `The combination of labels configured directly on the resource
 and default labels configured on the provider.`,
				Elem: &schema.Schema{Type: schema.TypeString},
			},
			"unique_id": {
				Type:     schema.TypeString,
				Computed: true,
				Description: `[Output only] The Google-generated UUID for the resource. This value is
unique across all regional multicast group consumer activation resources.
If a regional multicast group consumer activation is deleted and another
with the same name is created, the new regional multicast group consumer
activation is assigned a different unique_id.`,
			},
			"update_time": {
				Type:     schema.TypeString,
				Computed: true,
				Description: `[Output only] The timestamp when the regional multicast group consumer
activation was most recently updated.`,
			},
			"project": {
				Type:     schema.TypeString,
				Optional: true,
				Computed: true,
				ForceNew: true,
			},
			"deletion_policy": {
				Type:     schema.TypeString,
				Optional: true,
				Computed: true,
				Description: `Whether Terraform will be prevented from destroying the instance. Defaults to "DELETE".
When a 'terraform destroy' or 'terraform apply' would delete the instance,
the command will fail if this field is set to "PREVENT" in Terraform state.
When set to "ABANDON", the command will remove the resource from Terraform
management without updating or deleting the resource in the API.
When set to "DELETE", deleting the resource is allowed.
`,
			},
		},
		UseJSONNumber: true,
	}
}

func resourceNetworkServicesRegionalMulticastGroupConsumerActivationCreate(d *schema.ResourceData, meta interface{}) error {
	config := meta.(*transport_tpg.Config)
	userAgent, err := tpgresource.GenerateUserAgentString(d, config.UserAgent)
	if err != nil {
		return err
	}

	obj := make(map[string]interface{})
	descriptionProp, err := expandNetworkServicesRegionalMulticastGroupConsumerActivationDescription(d.Get("description"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("description"); !tpgresource.IsEmptyValue(reflect.ValueOf(descriptionProp)) && (ok || !reflect.DeepEqual(v, descriptionProp)) {
		obj["description"] = descriptionProp
	}
	interconnectAttachmentsProp, err := expandNetworkServicesRegionalMulticastGroupConsumerActivationInterconnectAttachments(d.Get("interconnect_attachments"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("interconnect_attachments"); !tpgresource.IsEmptyValue(reflect.ValueOf(interconnectAttachmentsProp)) && (ok || !reflect.DeepEqual(v, interconnectAttachmentsProp)) {
		obj["interconnectAttachments"] = interconnectAttachmentsProp
	}
	logConfigProp, err := expandNetworkServicesRegionalMulticastGroupConsumerActivationLogConfig(d.Get("log_config"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("log_config"); !tpgresource.IsEmptyValue(reflect.ValueOf(logConfigProp)) && (ok || !reflect.DeepEqual(v, logConfigProp)) {
		obj["logConfig"] = logConfigProp
	}
	regionalMulticastConsumerAssociationProp, err := expandNetworkServicesRegionalMulticastGroupConsumerActivationRegionalMulticastConsumerAssociation(d.Get("regional_multicast_consumer_association"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("regional_multicast_consumer_association"); !tpgresource.IsEmptyValue(reflect.ValueOf(regionalMulticastConsumerAssociationProp)) && (ok || !reflect.DeepEqual(v, regionalMulticastConsumerAssociationProp)) {
		obj["regionalMulticastConsumerAssociation"] = regionalMulticastConsumerAssociationProp
	}
	regionalMulticastGroupRangeActivationProp, err := expandNetworkServicesRegionalMulticastGroupConsumerActivationRegionalMulticastGroupRangeActivation(d.Get("regional_multicast_group_range_activation"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("regional_multicast_group_range_activation"); !tpgresource.IsEmptyValue(reflect.ValueOf(regionalMulticastGroupRangeActivationProp)) && (ok || !reflect.DeepEqual(v, regionalMulticastGroupRangeActivationProp)) {
		obj["regionalMulticastGroupRangeActivation"] = regionalMulticastGroupRangeActivationProp
	}
	effectiveLabelsProp, err := expandNetworkServicesRegionalMulticastGroupConsumerActivationEffectiveLabels(d.Get("effective_labels"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("effective_labels"); !tpgresource.IsEmptyValue(reflect.ValueOf(effectiveLabelsProp)) && (ok || !reflect.DeepEqual(v, effectiveLabelsProp)) {
		obj["labels"] = effectiveLabelsProp
	}

	url, err := tpgresource.ReplaceVars(d, config, transport_tpg.BaseUrl(Product, config)+"projects/{{project}}/locations/{{location}}/regionalMulticastGroupConsumerActivations?regionalMulticastGroupConsumerActivationId={{regional_multicast_group_consumer_activation_id}}")
	if err != nil {
		return err
	}

	log.Printf("[DEBUG] Creating new RegionalMulticastGroupConsumerActivation: %#v", obj)
	billingProject := ""

	project, err := tpgresource.GetProject(d, config)
	if err != nil {
		return fmt.Errorf("Error fetching project for RegionalMulticastGroupConsumerActivation: %s", err)
	}
	billingProject = project

	// err == nil indicates that the billing_project value was found
	if bp, err := tpgresource.GetBillingProject(d, config); err == nil {
		billingProject = bp
	}

	headers := make(http.Header)
	res, err := transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
		Config:    config,
		Method:    "POST",
		Project:   billingProject,
		RawURL:    url,
		UserAgent: userAgent,
		Body:      obj,
		Timeout:   d.Timeout(schema.TimeoutCreate),
		Headers:   headers,
	})
	if err != nil {
		return fmt.Errorf("Error creating RegionalMulticastGroupConsumerActivation: %s", err)
	}

	// Store the ID now
	id, err := tpgresource.ReplaceVars(d, config, "projects/{{project}}/locations/{{location}}/regionalMulticastGroupConsumerActivations/{{regional_multicast_group_consumer_activation_id}}")
	if err != nil {
		return fmt.Errorf("Error constructing id: %s", err)
	}
	d.SetId(id)

	err = NetworkServicesOperationWaitTime(
		config, res, project, "Creating RegionalMulticastGroupConsumerActivation", userAgent,
		d.Timeout(schema.TimeoutCreate))

	if err != nil {
		// The resource didn't actually create
		d.SetId("")
		return fmt.Errorf("Error waiting to create RegionalMulticastGroupConsumerActivation: %s", err)
	}

	log.Printf("[DEBUG] Finished creating RegionalMulticastGroupConsumerActivation %q: %#v", d.Id(), res)

	identity, err := d.Identity()
	if err == nil && identity != nil {
		if locationValue, ok := d.GetOk("location"); ok && locationValue.(string) != "" {
			if err = identity.Set("location", locationValue.(string)); err != nil {
				return fmt.Errorf("Error setting location: %s", err)
			}
		}
		if regionalMulticastGroupConsumerActivationIdValue, ok := d.GetOk("regional_multicast_group_consumer_activation_id"); ok && regionalMulticastGroupConsumerActivationIdValue.(string) != "" {
			if err = identity.Set("regional_multicast_group_consumer_activation_id", regionalMulticastGroupConsumerActivationIdValue.(string)); err != nil {
				return fmt.Errorf("Error setting regional_multicast_group_consumer_activation_id: %s", err)
			}
		}
		if projectValue, ok := d.GetOk("project"); ok && projectValue.(string) != "" {
			if err = identity.Set("project", projectValue.(string)); err != nil {
				return fmt.Errorf("Error setting project: %s", err)
			}
		}
	} else {
		log.Printf("[DEBUG] (Create) identity not set: %s", err)
	}

	return resourceNetworkServicesRegionalMulticastGroupConsumerActivationRead(d, meta)
}

func resourceNetworkServicesRegionalMulticastGroupConsumerActivationRead(d *schema.ResourceData, meta interface{}) error {
	config := meta.(*transport_tpg.Config)
	userAgent, err := tpgresource.GenerateUserAgentString(d, config.UserAgent)
	if err != nil {
		return err
	}

	url, err := tpgresource.ReplaceVars(d, config, transport_tpg.BaseUrl(Product, config)+"projects/{{project}}/locations/{{location}}/regionalMulticastGroupConsumerActivations/{{regional_multicast_group_consumer_activation_id}}")
	if err != nil {
		return err
	}

	billingProject := ""

	project, err := tpgresource.GetProject(d, config)
	if err != nil {
		return fmt.Errorf("Error fetching project for RegionalMulticastGroupConsumerActivation: %s", err)
	}
	billingProject = project

	// err == nil indicates that the billing_project value was found
	if bp, err := tpgresource.GetBillingProject(d, config); err == nil {
		billingProject = bp
	}

	headers := make(http.Header)
	res, err := transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
		Config:    config,
		Method:    "GET",
		Project:   billingProject,
		RawURL:    url,
		UserAgent: userAgent,
		Headers:   headers,
	})
	if err != nil {
		return transport_tpg.HandleNotFoundError(err, d, fmt.Sprintf("NetworkServicesRegionalMulticastGroupConsumerActivation %q", d.Id()))
	}

	log.Printf("[DEBUG] Finished reading NetworkServicesRegionalMulticastGroupConsumerActivation %q: %#v", d.Id(), res)

	// Explicitly set virtual fields to default values if unset
	if _, ok := d.GetOkExists("deletion_policy"); !ok {
		//prioritize config's value if present
		if config.DeletionPolicy != "" {
			if err := d.Set("deletion_policy", config.DeletionPolicy); err != nil {
				return fmt.Errorf("Error setting deletion_policy: %s", err)
			}
		} else {
			if err := d.Set("deletion_policy", "DELETE"); err != nil {
				return fmt.Errorf("Error setting deletion_policy: %s", err)
			}
		}
	}
	if err := d.Set("project", project); err != nil {
		return fmt.Errorf("Error reading RegionalMulticastGroupConsumerActivation: %s", err)
	}

	err = ResourceNetworkServicesRegionalMulticastGroupConsumerActivationFlatten(d, meta, res, config, project, userAgent, billingProject, url, headers)
	if err != nil {
		return err
	}

	identity, err := d.Identity()
	if err == nil && identity != nil {
		if v, ok := identity.GetOk("location"); !ok && v == "" {
			err = identity.Set("location", d.Get("location").(string))
			if err != nil {
				return fmt.Errorf("Error setting location: %s", err)
			}
		}
		if v, ok := identity.GetOk("regional_multicast_group_consumer_activation_id"); !ok && v == "" {
			err = identity.Set("regional_multicast_group_consumer_activation_id", d.Get("regional_multicast_group_consumer_activation_id").(string))
			if err != nil {
				return fmt.Errorf("Error setting regional_multicast_group_consumer_activation_id: %s", err)
			}
		}
		if v, ok := identity.GetOk("project"); !ok && v == "" {
			err = identity.Set("project", d.Get("project").(string))
			if err != nil {
				return fmt.Errorf("Error setting project: %s", err)
			}
		}
	} else {
		log.Printf("[DEBUG] (Read) identity not set: %s", err)
	}

	return nil
}

func resourceNetworkServicesRegionalMulticastGroupConsumerActivationUpdate(d *schema.ResourceData, meta interface{}) error {
	clientSideFields := map[string]bool{"deletion_policy": true}
	clientSideOnly := true
	for field := range ResourceNetworkServicesRegionalMulticastGroupConsumerActivation().Schema {
		if d.HasChange(field) && !clientSideFields[field] {
			clientSideOnly = false
			break
		}
	}
	if clientSideOnly {
		log.Print("[DEBUG] Only client-side changes detected. Cancelling update operation.")
		return resourceNetworkServicesRegionalMulticastGroupConsumerActivationRead(d, meta)
	}

	config := meta.(*transport_tpg.Config)
	userAgent, err := tpgresource.GenerateUserAgentString(d, config.UserAgent)
	if err != nil {
		return err
	}
	identity, err := d.Identity()
	if err == nil && identity != nil {
		if locationValue, ok := d.GetOk("location"); ok && locationValue.(string) != "" {
			if err = identity.Set("location", locationValue.(string)); err != nil {
				return fmt.Errorf("Error setting location: %s", err)
			}
		}
		if regionalMulticastGroupConsumerActivationIdValue, ok := d.GetOk("regional_multicast_group_consumer_activation_id"); ok && regionalMulticastGroupConsumerActivationIdValue.(string) != "" {
			if err = identity.Set("regional_multicast_group_consumer_activation_id", regionalMulticastGroupConsumerActivationIdValue.(string)); err != nil {
				return fmt.Errorf("Error setting regional_multicast_group_consumer_activation_id: %s", err)
			}
		}
		if projectValue, ok := d.GetOk("project"); ok && projectValue.(string) != "" {
			if err = identity.Set("project", projectValue.(string)); err != nil {
				return fmt.Errorf("Error setting project: %s", err)
			}
		}
	} else {
		log.Printf("[DEBUG] (Update) identity not set: %s", err)
	}

	billingProject := ""

	project, err := tpgresource.GetProject(d, config)
	if err != nil {
		return fmt.Errorf("Error fetching project for RegionalMulticastGroupConsumerActivation: %s", err)
	}
	billingProject = project

	obj := make(map[string]interface{})
	descriptionProp, err := expandNetworkServicesRegionalMulticastGroupConsumerActivationDescription(d.Get("description"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("description"); !tpgresource.IsEmptyValue(reflect.ValueOf(v)) && (ok || !reflect.DeepEqual(v, descriptionProp)) {
		obj["description"] = descriptionProp
	}
	interconnectAttachmentsProp, err := expandNetworkServicesRegionalMulticastGroupConsumerActivationInterconnectAttachments(d.Get("interconnect_attachments"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("interconnect_attachments"); !tpgresource.IsEmptyValue(reflect.ValueOf(v)) && (ok || !reflect.DeepEqual(v, interconnectAttachmentsProp)) {
		obj["interconnectAttachments"] = interconnectAttachmentsProp
	}
	logConfigProp, err := expandNetworkServicesRegionalMulticastGroupConsumerActivationLogConfig(d.Get("log_config"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("log_config"); !tpgresource.IsEmptyValue(reflect.ValueOf(v)) && (ok || !reflect.DeepEqual(v, logConfigProp)) {
		obj["logConfig"] = logConfigProp
	}
	effectiveLabelsProp, err := expandNetworkServicesRegionalMulticastGroupConsumerActivationEffectiveLabels(d.Get("effective_labels"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("effective_labels"); !tpgresource.IsEmptyValue(reflect.ValueOf(v)) && (ok || !reflect.DeepEqual(v, effectiveLabelsProp)) {
		obj["labels"] = effectiveLabelsProp
	}

	url, err := tpgresource.ReplaceVars(d, config, transport_tpg.BaseUrl(Product, config)+"projects/{{project}}/locations/{{location}}/regionalMulticastGroupConsumerActivations/{{regional_multicast_group_consumer_activation_id}}")
	if err != nil {
		return err
	}

	log.Printf("[DEBUG] Updating RegionalMulticastGroupConsumerActivation %q: %#v", d.Id(), obj)
	headers := make(http.Header)
	updateMask := []string{}

	if d.HasChange("description") {
		updateMask = append(updateMask, "description")
	}

	if d.HasChange("interconnect_attachments") {
		updateMask = append(updateMask, "interconnectAttachments")
	}

	if d.HasChange("log_config") {
		updateMask = append(updateMask, "logConfig")
	}

	if d.HasChange("effective_labels") {
		updateMask = append(updateMask, "labels")
	}
	// updateMask is a URL parameter but not present in the schema, so ReplaceVars
	// won't set it
	url, err = transport_tpg.AddQueryParams(url, map[string]string{"updateMask": strings.Join(updateMask, ",")})
	if err != nil {
		return err
	}

	// err == nil indicates that the billing_project value was found
	if bp, err := tpgresource.GetBillingProject(d, config); err == nil {
		billingProject = bp
	}

	// if updateMask is empty we are not updating anything so skip the post
	if len(updateMask) > 0 {
		res, err := transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
			Config:    config,
			Method:    "PATCH",
			Project:   billingProject,
			RawURL:    url,
			UserAgent: userAgent,
			Body:      obj,
			Timeout:   d.Timeout(schema.TimeoutUpdate),
			Headers:   headers,
		})

		if err != nil {
			return fmt.Errorf("Error updating RegionalMulticastGroupConsumerActivation %q: %s", d.Id(), err)
		} else {
			log.Printf("[DEBUG] Finished updating RegionalMulticastGroupConsumerActivation %q: %#v", d.Id(), res)
		}

		err = NetworkServicesOperationWaitTime(
			config, res, project, "Updating RegionalMulticastGroupConsumerActivation", userAgent,
			d.Timeout(schema.TimeoutUpdate))

		if err != nil {
			return err
		}
	}

	return resourceNetworkServicesRegionalMulticastGroupConsumerActivationRead(d, meta)
}

func resourceNetworkServicesRegionalMulticastGroupConsumerActivationDelete(d *schema.ResourceData, meta interface{}) error {
	if d.Get("deletion_policy").(string) == "PREVENT" {
		return fmt.Errorf("cannot destroy NetworkServicesRegionalMulticastGroupConsumerActivation without setting deletion_policy=\"DELETE\" and running `terraform apply`")
	}
	if d.Get("deletion_policy").(string) == "ABANDON" {
		log.Printf("[DEBUG] deletion_policy set to \"ABANDON\", removing RegionalMulticastGroupConsumerActivation %q from Terraform state without deletion", d.Id())
		return nil
	}
	config := meta.(*transport_tpg.Config)
	userAgent, err := tpgresource.GenerateUserAgentString(d, config.UserAgent)
	if err != nil {
		return err
	}

	billingProject := ""

	project, err := tpgresource.GetProject(d, config)
	if err != nil {
		return fmt.Errorf("Error fetching project for RegionalMulticastGroupConsumerActivation: %s", err)
	}
	billingProject = project
	url, err := tpgresource.ReplaceVars(d, config, transport_tpg.BaseUrl(Product, config)+"projects/{{project}}/locations/{{location}}/regionalMulticastGroupConsumerActivations/{{regional_multicast_group_consumer_activation_id}}")
	if err != nil {
		return err
	}

	var obj map[string]interface{}

	// err == nil indicates that the billing_project value was found
	if bp, err := tpgresource.GetBillingProject(d, config); err == nil {
		billingProject = bp
	}

	headers := make(http.Header)

	log.Printf("[DEBUG] Deleting RegionalMulticastGroupConsumerActivation %q", d.Id())
	res, err := transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
		Config:    config,
		Method:    "DELETE",
		Project:   billingProject,
		RawURL:    url,
		UserAgent: userAgent,
		Body:      obj,
		Timeout:   d.Timeout(schema.TimeoutDelete),
		Headers:   headers,
	})
	if err != nil {
		return transport_tpg.HandleNotFoundError(err, d, "RegionalMulticastGroupConsumerActivation")
	}

	err = NetworkServicesOperationWaitTime(
		config, res, project, "Deleting RegionalMulticastGroupConsumerActivation", userAgent,
		d.Timeout(schema.TimeoutDelete))

	if err != nil {
		return err
	}

	log.Printf("[DEBUG] Finished deleting RegionalMulticastGroupConsumerActivation %q: %#v", d.Id(), res)
	return nil
}

func resourceNetworkServicesRegionalMulticastGroupConsumerActivationImport(d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
	config := meta.(*transport_tpg.Config)
	if err := tpgresource.ParseImportId([]string{
		"^projects/(?P<project>[^/]+)/locations/(?P<location>[^/]+)/regionalMulticastGroupConsumerActivations/(?P<regional_multicast_group_consumer_activation_id>[^/]+)$",
		"^(?P<project>[^/]+)/(?P<location>[^/]+)/(?P<regional_multicast_group_consumer_activation_id>[^/]+)$",
		"^(?P<location>[^/]+)/(?P<regional_multicast_group_consumer_activation_id>[^/]+)$",
	}, d, config); err != nil {
		return nil, err
	}

	// Replace import id for the resource id
	id, err := tpgresource.ReplaceVars(d, config, "projects/{{project}}/locations/{{location}}/regionalMulticastGroupConsumerActivations/{{regional_multicast_group_consumer_activation_id}}")
	if err != nil {
		return nil, fmt.Errorf("Error constructing id: %s", err)
	}
	d.SetId(id)

	return []*schema.ResourceData{d}, nil
}

func flattenNetworkServicesRegionalMulticastGroupConsumerActivationCreateTime(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenNetworkServicesRegionalMulticastGroupConsumerActivationDescription(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenNetworkServicesRegionalMulticastGroupConsumerActivationInterconnectAttachments(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenNetworkServicesRegionalMulticastGroupConsumerActivationLabels(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return v
	}

	transformed := make(map[string]interface{})
	if l, ok := d.GetOkExists("labels"); ok {
		for k := range l.(map[string]interface{}) {
			transformed[k] = v.(map[string]interface{})[k]
		}
	}

	return transformed
}

func flattenNetworkServicesRegionalMulticastGroupConsumerActivationLogConfig(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	original := v.(map[string]interface{})
	if len(original) == 0 {
		return nil
	}
	transformed := make(map[string]interface{})
	transformed["enabled"] =
		flattenNetworkServicesRegionalMulticastGroupConsumerActivationLogConfigEnabled(original["enabled"], d, config)
	return []interface{}{transformed}
}
func flattenNetworkServicesRegionalMulticastGroupConsumerActivationLogConfigEnabled(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenNetworkServicesRegionalMulticastGroupConsumerActivationName(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenNetworkServicesRegionalMulticastGroupConsumerActivationRegionalMulticastConsumerAssociation(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenNetworkServicesRegionalMulticastGroupConsumerActivationRegionalMulticastGroupRangeActivation(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenNetworkServicesRegionalMulticastGroupConsumerActivationState(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	original := v.(map[string]interface{})
	if len(original) == 0 {
		return nil
	}
	transformed := make(map[string]interface{})
	transformed["state"] =
		flattenNetworkServicesRegionalMulticastGroupConsumerActivationStateState(original["state"], d, config)
	return []interface{}{transformed}
}
func flattenNetworkServicesRegionalMulticastGroupConsumerActivationStateState(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenNetworkServicesRegionalMulticastGroupConsumerActivationUniqueId(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenNetworkServicesRegionalMulticastGroupConsumerActivationUpdateTime(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenNetworkServicesRegionalMulticastGroupConsumerActivationTerraformLabels(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return v
	}

	transformed := make(map[string]interface{})
	if l, ok := d.GetOkExists("terraform_labels"); ok {
		for k := range l.(map[string]interface{}) {
			transformed[k] = v.(map[string]interface{})[k]
		}
	}

	return transformed
}

func flattenNetworkServicesRegionalMulticastGroupConsumerActivationEffectiveLabels(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func expandNetworkServicesRegionalMulticastGroupConsumerActivationDescription(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandNetworkServicesRegionalMulticastGroupConsumerActivationInterconnectAttachments(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandNetworkServicesRegionalMulticastGroupConsumerActivationLogConfig(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	if v == nil {
		return nil, nil
	}
	l := v.([]interface{})
	if len(l) == 0 || l[0] == nil {
		return nil, nil
	}
	raw := l[0]
	original := raw.(map[string]interface{})
	transformed := make(map[string]interface{})

	transformedEnabled, err := expandNetworkServicesRegionalMulticastGroupConsumerActivationLogConfigEnabled(original["enabled"], d, config)
	if err != nil {
		return nil, err
	} else if val := reflect.ValueOf(transformedEnabled); val.IsValid() && !tpgresource.IsEmptyValue(val) {
		transformed["enabled"] = transformedEnabled
	}

	return transformed, nil
}

func expandNetworkServicesRegionalMulticastGroupConsumerActivationLogConfigEnabled(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandNetworkServicesRegionalMulticastGroupConsumerActivationRegionalMulticastConsumerAssociation(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandNetworkServicesRegionalMulticastGroupConsumerActivationRegionalMulticastGroupRangeActivation(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandNetworkServicesRegionalMulticastGroupConsumerActivationEffectiveLabels(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (map[string]string, error) {
	if v == nil {
		return map[string]string{}, nil
	}
	m := make(map[string]string)
	for k, val := range v.(map[string]interface{}) {
		m[k] = val.(string)
	}
	return m, nil
}

func ResourceNetworkServicesRegionalMulticastGroupConsumerActivationFlatten(d *schema.ResourceData, meta interface{}, res map[string]interface{}, config *transport_tpg.Config, project string, userAgent string, billingProject string, url string, headers http.Header) error {
	var err error

	if err = d.Set("create_time", flattenNetworkServicesRegionalMulticastGroupConsumerActivationCreateTime(res["createTime"], d, config)); err != nil {
		return fmt.Errorf("Error reading RegionalMulticastGroupConsumerActivation: %s", err)
	}
	if err = d.Set("description", flattenNetworkServicesRegionalMulticastGroupConsumerActivationDescription(res["description"], d, config)); err != nil {
		return fmt.Errorf("Error reading RegionalMulticastGroupConsumerActivation: %s", err)
	}
	if err = d.Set("interconnect_attachments", flattenNetworkServicesRegionalMulticastGroupConsumerActivationInterconnectAttachments(res["interconnectAttachments"], d, config)); err != nil {
		return fmt.Errorf("Error reading RegionalMulticastGroupConsumerActivation: %s", err)
	}
	if err = d.Set("labels", flattenNetworkServicesRegionalMulticastGroupConsumerActivationLabels(res["labels"], d, config)); err != nil {
		return fmt.Errorf("Error reading RegionalMulticastGroupConsumerActivation: %s", err)
	}
	if err = d.Set("log_config", flattenNetworkServicesRegionalMulticastGroupConsumerActivationLogConfig(res["logConfig"], d, config)); err != nil {
		return fmt.Errorf("Error reading RegionalMulticastGroupConsumerActivation: %s", err)
	}
	if err = d.Set("name", flattenNetworkServicesRegionalMulticastGroupConsumerActivationName(res["name"], d, config)); err != nil {
		return fmt.Errorf("Error reading RegionalMulticastGroupConsumerActivation: %s", err)
	}
	if err = d.Set("regional_multicast_consumer_association", flattenNetworkServicesRegionalMulticastGroupConsumerActivationRegionalMulticastConsumerAssociation(res["regionalMulticastConsumerAssociation"], d, config)); err != nil {
		return fmt.Errorf("Error reading RegionalMulticastGroupConsumerActivation: %s", err)
	}
	if err = d.Set("regional_multicast_group_range_activation", flattenNetworkServicesRegionalMulticastGroupConsumerActivationRegionalMulticastGroupRangeActivation(res["regionalMulticastGroupRangeActivation"], d, config)); err != nil {
		return fmt.Errorf("Error reading RegionalMulticastGroupConsumerActivation: %s", err)
	}
	if err = d.Set("state", flattenNetworkServicesRegionalMulticastGroupConsumerActivationState(res["state"], d, config)); err != nil {
		return fmt.Errorf("Error reading RegionalMulticastGroupConsumerActivation: %s", err)
	}
	if err = d.Set("unique_id", flattenNetworkServicesRegionalMulticastGroupConsumerActivationUniqueId(res["uniqueId"], d, config)); err != nil {
		return fmt.Errorf("Error reading RegionalMulticastGroupConsumerActivation: %s", err)
	}
	if err = d.Set("update_time", flattenNetworkServicesRegionalMulticastGroupConsumerActivationUpdateTime(res["updateTime"], d, config)); err != nil {
		return fmt.Errorf("Error reading RegionalMulticastGroupConsumerActivation: %s", err)
	}
	if err = d.Set("terraform_labels", flattenNetworkServicesRegionalMulticastGroupConsumerActivationTerraformLabels(res["labels"], d, config)); err != nil {
		return fmt.Errorf("Error reading RegionalMulticastGroupConsumerActivation: %s", err)
	}
	if err = d.Set("effective_labels", flattenNetworkServicesRegionalMulticastGroupConsumerActivationEffectiveLabels(res["labels"], d, config)); err != nil {
		return fmt.Errorf("Error reading RegionalMulticastGroupConsumerActivation: %s", err)
	}

	return nil
}
