// Copyright IBM Corp. 2014, 2026
// Copyright 2026 Google LLC
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package networkservices_test

import (
	"fmt"
	"log"
	"regexp"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"

	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/acctest"
	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/envvar"
	_ "github.com/hashicorp/terraform-provider-google-nightly/google-nightly/services/compute"
	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/services/networkservices"
	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/tpgresource"
	transport_tpg "github.com/hashicorp/terraform-provider-google-nightly/google-nightly/transport"

	"google.golang.org/api/googleapi"
)

var (
	_ = fmt.Sprintf
	_ = log.Print
	_ = regexp.MatchString
	_ = strconv.Atoi
	_ = strings.Trim
	_ = time.Now
	_ = resource.TestMain
	_ = terraform.NewState
	_ = envvar.TestEnvVar
	_ = tpgresource.SetLabels
	_ = transport_tpg.Config{}
	_ = googleapi.Error{}
	_ = networkservices.Product
)

func TestAccNetworkServicesRegionalMulticastConsumerAssociation_networkServicesRegionalMulticastConsumerAssociationBasicExample(t *testing.T) {
	t.Parallel()

	randomSuffix := acctest.RandString(t, 10)

	context := map[string]interface{}{
		"consumer_association_name": "tf-test-test-consumer-association-rmca" + randomSuffix,
		"domain_activation_name":    "tf-test-test-domain-activation-rmca" + randomSuffix,
		"domain_name":               "tf-test-test-domain-rmca" + randomSuffix,
		"network_name":              "tf-test-test-network-rmca" + randomSuffix,
		"random_suffix":             randomSuffix,
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderBetaFactories(t),
		CheckDestroy:             testAccCheckNetworkServicesRegionalMulticastConsumerAssociationDestroyProducer(t),
		Steps: []resource.TestStep{
			{
				Config: testAccNetworkServicesRegionalMulticastConsumerAssociation_networkServicesRegionalMulticastConsumerAssociationBasicExample(context),
			},
			{
				ResourceName:            "google_network_services_regional_multicast_consumer_association.rmca_test",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"labels", "location", "regional_multicast_consumer_association_id", "terraform_labels"},
			},
			{
				ResourceName:       "google_network_services_regional_multicast_consumer_association.rmca_test",
				RefreshState:       true,
				ExpectNonEmptyPlan: true,
				ImportStateKind:    resource.ImportBlockWithResourceIdentity,
			},
		},
	})
}

func testAccNetworkServicesRegionalMulticastConsumerAssociation_networkServicesRegionalMulticastConsumerAssociationBasicExample(context map[string]interface{}) string {
	return acctest.Nprintf(`
resource "google_compute_network" "default" {
  name                    = "%{network_name}"
  auto_create_subnetworks = false
}

resource "google_network_services_multicast_domain" "default" {
  multicast_domain_id = "%{domain_name}"
  location            = "global"
  admin_network       = google_compute_network.default.id
}

resource "google_network_services_regional_multicast_domain_activation" "default" {
  regional_multicast_domain_activation_id = "%{domain_activation_name}"
  location                                = "us-central1"
  multicast_domain                        = google_network_services_multicast_domain.default.id
  pim_spec {
    pim_mode                  = "PIM_MODE_SPARSE"
    multicast_source_location = "MULTICAST_SOURCE_GCP"
  }
}

resource "google_network_services_regional_multicast_consumer_association" rmca_test {
  regional_multicast_consumer_association_id = "%{consumer_association_name}"
  location                                   = "us-central1"
  network                                    = google_compute_network.default.id
  regional_multicast_domain_activation       = google_network_services_regional_multicast_domain_activation.default.id
}
`, context)
}

func testAccCheckNetworkServicesRegionalMulticastConsumerAssociationDestroyProducer(t *testing.T) func(s *terraform.State) error {
	return func(s *terraform.State) error {
		for name, rs := range s.RootModule().Resources {
			if rs.Type != "google_network_services_regional_multicast_consumer_association" {
				continue
			}
			if strings.HasPrefix(name, "data.") {
				continue
			}

			config := acctest.GoogleProviderConfig(t)
			url, err := tpgresource.ReplaceVarsForTest(config, rs, transport_tpg.BaseUrl(networkservices.Product, config)+"projects/{{project}}/locations/{{location}}/regionalMulticastConsumerAssociations/{{regional_multicast_consumer_association_id}}")
			if err != nil {
				return err
			}

			billingProject := ""

			if config.BillingProject != "" {
				billingProject = config.BillingProject
			}

			_, err = transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
				Config:    config,
				Method:    "GET",
				Project:   billingProject,
				RawURL:    url,
				UserAgent: config.UserAgent,
			})
			if err == nil {
				return fmt.Errorf("NetworkServicesRegionalMulticastConsumerAssociation still exists at %s", url)
			}
		}

		return nil
	}
}
