// Copyright IBM Corp. 2014, 2026
// Copyright 2026 Google LLC
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This code is generated by Magic Modules using the following:
//
//     Configuration: https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/products/networkservices/RegionalMulticastProducerAssociation.yaml
//     Template:      https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/resource.go.tmpl
//
//     DO NOT EDIT this file directly. Any changes made to this file will be
//     overwritten during the next generation cycle.
//
// ----------------------------------------------------------------------------

package networkservices

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"reflect"
	"regexp"
	"slices"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/hashicorp/errwrap"
	"github.com/hashicorp/go-cty/cty"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/customdiff"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/id"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/logging"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/retry"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/structure"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	"github.com/hashicorp/terraform-plugin-sdk/v2/terraform"
	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/registry"
	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/tpgresource"
	transport_tpg "github.com/hashicorp/terraform-provider-google-nightly/google-nightly/transport"
	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/verify"

	"google.golang.org/api/googleapi"
)

var (
	_ = bytes.Clone
	_ = context.WithCancel
	_ = base64.NewDecoder
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = log.Print
	_ = http.Get
	_ = reflect.ValueOf
	_ = regexp.Match
	_ = slices.Min([]int{1})
	_ = sort.IntSlice{}
	_ = strconv.Atoi
	_ = strings.Trim
	_ = time.Now
	_ = errwrap.Wrap
	_ = cty.BoolVal
	_ = diag.Diagnostic{}
	_ = customdiff.All
	_ = id.UniqueId
	_ = logging.LogLevel
	_ = retry.Retry
	_ = schema.Noop
	_ = validation.All
	_ = structure.ExpandJsonFromString
	_ = terraform.State{}
	_ = tpgresource.SetLabels
	_ = transport_tpg.Config{}
	_ = verify.ValidateEnum
	_ = googleapi.Error{}
)

func init() {
	registry.Schema{
		Name:        "google_network_services_regional_multicast_producer_association",
		ProductName: "networkservices",
		Type:        registry.SchemaTypeResource,
		Schema:      ResourceNetworkServicesRegionalMulticastProducerAssociation(),
	}.Register()
}

func ResourceNetworkServicesRegionalMulticastProducerAssociation() *schema.Resource {
	return &schema.Resource{
		Create: resourceNetworkServicesRegionalMulticastProducerAssociationCreate,
		Read:   resourceNetworkServicesRegionalMulticastProducerAssociationRead,
		Update: resourceNetworkServicesRegionalMulticastProducerAssociationUpdate,
		Delete: resourceNetworkServicesRegionalMulticastProducerAssociationDelete,

		Importer: &schema.ResourceImporter{
			State: resourceNetworkServicesRegionalMulticastProducerAssociationImport,
		},

		Timeouts: &schema.ResourceTimeout{
			Create: schema.DefaultTimeout(20 * time.Minute),
			Update: schema.DefaultTimeout(20 * time.Minute),
			Delete: schema.DefaultTimeout(20 * time.Minute),
		},

		CustomizeDiff: customdiff.All(
			tpgresource.SetLabelsDiff,
			tpgresource.DefaultProviderProject,
			tpgresource.DefaultProviderDeletionPolicy("DELETE"),
		),

		Identity: &schema.ResourceIdentity{
			Version: 1,
			SchemaFunc: func() map[string]*schema.Schema {
				return map[string]*schema.Schema{
					"location": {
						Type:              schema.TypeString,
						RequiredForImport: true,
					},
					"regional_multicast_producer_association_id": {
						Type:              schema.TypeString,
						RequiredForImport: true,
					},
					"project": {
						Type:              schema.TypeString,
						OptionalForImport: true,
					},
				}
			},
		},
		ResourceBehavior: schema.ResourceBehavior{
			MutableIdentity: true,
		},

		Schema: map[string]*schema.Schema{
			"location": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: `Resource ID segment making up resource 'name'. It identifies the resource within its parent collection as described in https://google.aip.dev/122.`,
			},
			"network": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
				Description: `The resource name of the multicast producer VPC network.
Use the following format:
'projects/{project}/locations/global/networks/{network}'.`,
			},
			"regional_multicast_domain_activation": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
				Description: `The resource name of the regional multicast domain activation that is in
the same region as this regional multicast producer association.
Use the following format:
'projects/*/locations/*/regionalMulticastDomainActivations/*'.`,
			},
			"regional_multicast_producer_association_id": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
				Description: `A unique name for the regional multicast producer association.
The name is restricted to lower-case letters, numbers, and hyphen, with
the first character a lower-case letter, and the last a letter or a
number. The name must not exceed 63 characters.`,
			},
			"description": {
				Type:     schema.TypeString,
				Optional: true,
				Description: `An optional text description of the regional multicast producer
association.`,
			},
			"labels": {
				Type:     schema.TypeMap,
				Optional: true,
				Description: `Labels as key-value pairs

**Note**: This field is non-authoritative, and will only manage the labels present in your configuration.
Please refer to the field 'effective_labels' for all of the labels present on the resource.`,
				Elem: &schema.Schema{Type: schema.TypeString},
			},
			"create_time": {
				Type:     schema.TypeString,
				Computed: true,
				Description: `[Output only] The timestamp when the regional multicast producer
association was created.`,
			},
			"effective_labels": {
				Type:        schema.TypeMap,
				Computed:    true,
				Description: `All of labels (key/value pairs) present on the resource in GCP, including the labels configured through Terraform, other clients and services.`,
				Elem:        &schema.Schema{Type: schema.TypeString},
			},
			"name": {
				Type:     schema.TypeString,
				Computed: true,
				Description: `Identifier. The resource name of the regional multicast producer association.
Use the following format:
'projects/*/locations/*/regionalMulticastProducerAssociations/*'.`,
			},
			"state": {
				Type:        schema.TypeList,
				Computed:    true,
				Description: `The multicast resource's state.`,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"state": {
							Type:     schema.TypeString,
							Computed: true,
							Description: `The state of the multicast resource.
Possible values:
CREATING
ACTIVE
DELETING
DELETE_FAILED
UPDATING
UPDATE_FAILED
INACTIVE
OBSOLETE`,
						},
					},
				},
			},
			"terraform_labels": {
				Type:     schema.TypeMap,
				Computed: true,
				Description: `The combination of labels configured directly on the resource
 and default labels configured on the provider.`,
				Elem: &schema.Schema{Type: schema.TypeString},
			},
			"unique_id": {
				Type:     schema.TypeString,
				Computed: true,
				Description: `[Output only] The Google-generated UUID for the resource. This value is
unique across all regional multicast producer association resources. If a
regional multicast producer association is deleted and another with the
same name is created, the new regional multicast producer association is
assigned a different unique_id.`,
			},
			"update_time": {
				Type:     schema.TypeString,
				Computed: true,
				Description: `[Output only] The timestamp when the regional multicast producer
association was most recently updated.`,
			},
			"project": {
				Type:     schema.TypeString,
				Optional: true,
				Computed: true,
				ForceNew: true,
			},
			"deletion_policy": {
				Type:     schema.TypeString,
				Optional: true,
				Computed: true,
				Description: `Whether Terraform will be prevented from destroying the instance. Defaults to "DELETE".
When a 'terraform destroy' or 'terraform apply' would delete the instance,
the command will fail if this field is set to "PREVENT" in Terraform state.
When set to "ABANDON", the command will remove the resource from Terraform
management without updating or deleting the resource in the API.
When set to "DELETE", deleting the resource is allowed.
`,
			},
		},
		UseJSONNumber: true,
	}
}

func resourceNetworkServicesRegionalMulticastProducerAssociationCreate(d *schema.ResourceData, meta interface{}) error {
	config := meta.(*transport_tpg.Config)
	userAgent, err := tpgresource.GenerateUserAgentString(d, config.UserAgent)
	if err != nil {
		return err
	}

	obj := make(map[string]interface{})
	descriptionProp, err := expandNetworkServicesRegionalMulticastProducerAssociationDescription(d.Get("description"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("description"); !tpgresource.IsEmptyValue(reflect.ValueOf(descriptionProp)) && (ok || !reflect.DeepEqual(v, descriptionProp)) {
		obj["description"] = descriptionProp
	}
	networkProp, err := expandNetworkServicesRegionalMulticastProducerAssociationNetwork(d.Get("network"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("network"); !tpgresource.IsEmptyValue(reflect.ValueOf(networkProp)) && (ok || !reflect.DeepEqual(v, networkProp)) {
		obj["network"] = networkProp
	}
	regionalMulticastDomainActivationProp, err := expandNetworkServicesRegionalMulticastProducerAssociationRegionalMulticastDomainActivation(d.Get("regional_multicast_domain_activation"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("regional_multicast_domain_activation"); !tpgresource.IsEmptyValue(reflect.ValueOf(regionalMulticastDomainActivationProp)) && (ok || !reflect.DeepEqual(v, regionalMulticastDomainActivationProp)) {
		obj["regionalMulticastDomainActivation"] = regionalMulticastDomainActivationProp
	}
	effectiveLabelsProp, err := expandNetworkServicesRegionalMulticastProducerAssociationEffectiveLabels(d.Get("effective_labels"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("effective_labels"); !tpgresource.IsEmptyValue(reflect.ValueOf(effectiveLabelsProp)) && (ok || !reflect.DeepEqual(v, effectiveLabelsProp)) {
		obj["labels"] = effectiveLabelsProp
	}

	url, err := tpgresource.ReplaceVars(d, config, transport_tpg.BaseUrl(Product, config)+"projects/{{project}}/locations/{{location}}/regionalMulticastProducerAssociations?regionalMulticastProducerAssociationId={{regional_multicast_producer_association_id}}")
	if err != nil {
		return err
	}

	log.Printf("[DEBUG] Creating new RegionalMulticastProducerAssociation: %#v", obj)
	billingProject := ""

	project, err := tpgresource.GetProject(d, config)
	if err != nil {
		return fmt.Errorf("Error fetching project for RegionalMulticastProducerAssociation: %s", err)
	}
	billingProject = project

	// err == nil indicates that the billing_project value was found
	if bp, err := tpgresource.GetBillingProject(d, config); err == nil {
		billingProject = bp
	}

	headers := make(http.Header)
	res, err := transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
		Config:    config,
		Method:    "POST",
		Project:   billingProject,
		RawURL:    url,
		UserAgent: userAgent,
		Body:      obj,
		Timeout:   d.Timeout(schema.TimeoutCreate),
		Headers:   headers,
	})
	if err != nil {
		return fmt.Errorf("Error creating RegionalMulticastProducerAssociation: %s", err)
	}

	// Store the ID now
	id, err := tpgresource.ReplaceVars(d, config, "projects/{{project}}/locations/{{location}}/regionalMulticastProducerAssociations/{{regional_multicast_producer_association_id}}")
	if err != nil {
		return fmt.Errorf("Error constructing id: %s", err)
	}
	d.SetId(id)

	err = NetworkServicesOperationWaitTime(
		config, res, project, "Creating RegionalMulticastProducerAssociation", userAgent,
		d.Timeout(schema.TimeoutCreate))

	if err != nil {
		// The resource didn't actually create
		d.SetId("")
		return fmt.Errorf("Error waiting to create RegionalMulticastProducerAssociation: %s", err)
	}

	log.Printf("[DEBUG] Finished creating RegionalMulticastProducerAssociation %q: %#v", d.Id(), res)

	identity, err := d.Identity()
	if err == nil && identity != nil {
		if locationValue, ok := d.GetOk("location"); ok && locationValue.(string) != "" {
			if err = identity.Set("location", locationValue.(string)); err != nil {
				return fmt.Errorf("Error setting location: %s", err)
			}
		}
		if regionalMulticastProducerAssociationIdValue, ok := d.GetOk("regional_multicast_producer_association_id"); ok && regionalMulticastProducerAssociationIdValue.(string) != "" {
			if err = identity.Set("regional_multicast_producer_association_id", regionalMulticastProducerAssociationIdValue.(string)); err != nil {
				return fmt.Errorf("Error setting regional_multicast_producer_association_id: %s", err)
			}
		}
		if projectValue, ok := d.GetOk("project"); ok && projectValue.(string) != "" {
			if err = identity.Set("project", projectValue.(string)); err != nil {
				return fmt.Errorf("Error setting project: %s", err)
			}
		}
	} else {
		log.Printf("[DEBUG] (Create) identity not set: %s", err)
	}

	return resourceNetworkServicesRegionalMulticastProducerAssociationRead(d, meta)
}

func resourceNetworkServicesRegionalMulticastProducerAssociationRead(d *schema.ResourceData, meta interface{}) error {
	config := meta.(*transport_tpg.Config)
	userAgent, err := tpgresource.GenerateUserAgentString(d, config.UserAgent)
	if err != nil {
		return err
	}

	url, err := tpgresource.ReplaceVars(d, config, transport_tpg.BaseUrl(Product, config)+"projects/{{project}}/locations/{{location}}/regionalMulticastProducerAssociations/{{regional_multicast_producer_association_id}}")
	if err != nil {
		return err
	}

	billingProject := ""

	project, err := tpgresource.GetProject(d, config)
	if err != nil {
		return fmt.Errorf("Error fetching project for RegionalMulticastProducerAssociation: %s", err)
	}
	billingProject = project

	// err == nil indicates that the billing_project value was found
	if bp, err := tpgresource.GetBillingProject(d, config); err == nil {
		billingProject = bp
	}

	headers := make(http.Header)
	res, err := transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
		Config:    config,
		Method:    "GET",
		Project:   billingProject,
		RawURL:    url,
		UserAgent: userAgent,
		Headers:   headers,
	})
	if err != nil {
		return transport_tpg.HandleNotFoundError(err, d, fmt.Sprintf("NetworkServicesRegionalMulticastProducerAssociation %q", d.Id()))
	}

	log.Printf("[DEBUG] Finished reading NetworkServicesRegionalMulticastProducerAssociation %q: %#v", d.Id(), res)

	// Explicitly set virtual fields to default values if unset
	if _, ok := d.GetOkExists("deletion_policy"); !ok {
		//prioritize config's value if present
		if config.DeletionPolicy != "" {
			if err := d.Set("deletion_policy", config.DeletionPolicy); err != nil {
				return fmt.Errorf("Error setting deletion_policy: %s", err)
			}
		} else {
			if err := d.Set("deletion_policy", "DELETE"); err != nil {
				return fmt.Errorf("Error setting deletion_policy: %s", err)
			}
		}
	}
	if err := d.Set("project", project); err != nil {
		return fmt.Errorf("Error reading RegionalMulticastProducerAssociation: %s", err)
	}

	err = ResourceNetworkServicesRegionalMulticastProducerAssociationFlatten(d, meta, res, config, project, userAgent, billingProject, url, headers)
	if err != nil {
		return err
	}

	identity, err := d.Identity()
	if err == nil && identity != nil {
		if v, ok := identity.GetOk("location"); !ok && v == "" {
			err = identity.Set("location", d.Get("location").(string))
			if err != nil {
				return fmt.Errorf("Error setting location: %s", err)
			}
		}
		if v, ok := identity.GetOk("regional_multicast_producer_association_id"); !ok && v == "" {
			err = identity.Set("regional_multicast_producer_association_id", d.Get("regional_multicast_producer_association_id").(string))
			if err != nil {
				return fmt.Errorf("Error setting regional_multicast_producer_association_id: %s", err)
			}
		}
		if v, ok := identity.GetOk("project"); !ok && v == "" {
			err = identity.Set("project", d.Get("project").(string))
			if err != nil {
				return fmt.Errorf("Error setting project: %s", err)
			}
		}
	} else {
		log.Printf("[DEBUG] (Read) identity not set: %s", err)
	}

	return nil
}

func resourceNetworkServicesRegionalMulticastProducerAssociationUpdate(d *schema.ResourceData, meta interface{}) error {
	clientSideFields := map[string]bool{"deletion_policy": true}
	clientSideOnly := true
	for field := range ResourceNetworkServicesRegionalMulticastProducerAssociation().Schema {
		if d.HasChange(field) && !clientSideFields[field] {
			clientSideOnly = false
			break
		}
	}
	if clientSideOnly {
		log.Print("[DEBUG] Only client-side changes detected. Cancelling update operation.")
		return resourceNetworkServicesRegionalMulticastProducerAssociationRead(d, meta)
	}

	config := meta.(*transport_tpg.Config)
	userAgent, err := tpgresource.GenerateUserAgentString(d, config.UserAgent)
	if err != nil {
		return err
	}
	identity, err := d.Identity()
	if err == nil && identity != nil {
		if locationValue, ok := d.GetOk("location"); ok && locationValue.(string) != "" {
			if err = identity.Set("location", locationValue.(string)); err != nil {
				return fmt.Errorf("Error setting location: %s", err)
			}
		}
		if regionalMulticastProducerAssociationIdValue, ok := d.GetOk("regional_multicast_producer_association_id"); ok && regionalMulticastProducerAssociationIdValue.(string) != "" {
			if err = identity.Set("regional_multicast_producer_association_id", regionalMulticastProducerAssociationIdValue.(string)); err != nil {
				return fmt.Errorf("Error setting regional_multicast_producer_association_id: %s", err)
			}
		}
		if projectValue, ok := d.GetOk("project"); ok && projectValue.(string) != "" {
			if err = identity.Set("project", projectValue.(string)); err != nil {
				return fmt.Errorf("Error setting project: %s", err)
			}
		}
	} else {
		log.Printf("[DEBUG] (Update) identity not set: %s", err)
	}

	billingProject := ""

	project, err := tpgresource.GetProject(d, config)
	if err != nil {
		return fmt.Errorf("Error fetching project for RegionalMulticastProducerAssociation: %s", err)
	}
	billingProject = project

	obj := make(map[string]interface{})
	descriptionProp, err := expandNetworkServicesRegionalMulticastProducerAssociationDescription(d.Get("description"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("description"); !tpgresource.IsEmptyValue(reflect.ValueOf(v)) && (ok || !reflect.DeepEqual(v, descriptionProp)) {
		obj["description"] = descriptionProp
	}
	effectiveLabelsProp, err := expandNetworkServicesRegionalMulticastProducerAssociationEffectiveLabels(d.Get("effective_labels"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("effective_labels"); !tpgresource.IsEmptyValue(reflect.ValueOf(v)) && (ok || !reflect.DeepEqual(v, effectiveLabelsProp)) {
		obj["labels"] = effectiveLabelsProp
	}

	url, err := tpgresource.ReplaceVars(d, config, transport_tpg.BaseUrl(Product, config)+"projects/{{project}}/locations/{{location}}/regionalMulticastProducerAssociations/{{regional_multicast_producer_association_id}}")
	if err != nil {
		return err
	}

	log.Printf("[DEBUG] Updating RegionalMulticastProducerAssociation %q: %#v", d.Id(), obj)
	headers := make(http.Header)
	updateMask := []string{}

	if d.HasChange("description") {
		updateMask = append(updateMask, "description")
	}

	if d.HasChange("effective_labels") {
		updateMask = append(updateMask, "labels")
	}
	// updateMask is a URL parameter but not present in the schema, so ReplaceVars
	// won't set it
	url, err = transport_tpg.AddQueryParams(url, map[string]string{"updateMask": strings.Join(updateMask, ",")})
	if err != nil {
		return err
	}

	// err == nil indicates that the billing_project value was found
	if bp, err := tpgresource.GetBillingProject(d, config); err == nil {
		billingProject = bp
	}

	// if updateMask is empty we are not updating anything so skip the post
	if len(updateMask) > 0 {
		res, err := transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
			Config:    config,
			Method:    "PATCH",
			Project:   billingProject,
			RawURL:    url,
			UserAgent: userAgent,
			Body:      obj,
			Timeout:   d.Timeout(schema.TimeoutUpdate),
			Headers:   headers,
		})

		if err != nil {
			return fmt.Errorf("Error updating RegionalMulticastProducerAssociation %q: %s", d.Id(), err)
		} else {
			log.Printf("[DEBUG] Finished updating RegionalMulticastProducerAssociation %q: %#v", d.Id(), res)
		}

		err = NetworkServicesOperationWaitTime(
			config, res, project, "Updating RegionalMulticastProducerAssociation", userAgent,
			d.Timeout(schema.TimeoutUpdate))

		if err != nil {
			return err
		}
	}

	return resourceNetworkServicesRegionalMulticastProducerAssociationRead(d, meta)
}

func resourceNetworkServicesRegionalMulticastProducerAssociationDelete(d *schema.ResourceData, meta interface{}) error {
	if d.Get("deletion_policy").(string) == "PREVENT" {
		return fmt.Errorf("cannot destroy NetworkServicesRegionalMulticastProducerAssociation without setting deletion_policy=\"DELETE\" and running `terraform apply`")
	}
	if d.Get("deletion_policy").(string) == "ABANDON" {
		log.Printf("[DEBUG] deletion_policy set to \"ABANDON\", removing RegionalMulticastProducerAssociation %q from Terraform state without deletion", d.Id())
		return nil
	}
	config := meta.(*transport_tpg.Config)
	userAgent, err := tpgresource.GenerateUserAgentString(d, config.UserAgent)
	if err != nil {
		return err
	}

	billingProject := ""

	project, err := tpgresource.GetProject(d, config)
	if err != nil {
		return fmt.Errorf("Error fetching project for RegionalMulticastProducerAssociation: %s", err)
	}
	billingProject = project
	url, err := tpgresource.ReplaceVars(d, config, transport_tpg.BaseUrl(Product, config)+"projects/{{project}}/locations/{{location}}/regionalMulticastProducerAssociations/{{regional_multicast_producer_association_id}}")
	if err != nil {
		return err
	}

	var obj map[string]interface{}

	// err == nil indicates that the billing_project value was found
	if bp, err := tpgresource.GetBillingProject(d, config); err == nil {
		billingProject = bp
	}

	headers := make(http.Header)

	log.Printf("[DEBUG] Deleting RegionalMulticastProducerAssociation %q", d.Id())
	res, err := transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
		Config:    config,
		Method:    "DELETE",
		Project:   billingProject,
		RawURL:    url,
		UserAgent: userAgent,
		Body:      obj,
		Timeout:   d.Timeout(schema.TimeoutDelete),
		Headers:   headers,
	})
	if err != nil {
		return transport_tpg.HandleNotFoundError(err, d, "RegionalMulticastProducerAssociation")
	}

	err = NetworkServicesOperationWaitTime(
		config, res, project, "Deleting RegionalMulticastProducerAssociation", userAgent,
		d.Timeout(schema.TimeoutDelete))

	if err != nil {
		return err
	}

	log.Printf("[DEBUG] Finished deleting RegionalMulticastProducerAssociation %q: %#v", d.Id(), res)
	return nil
}

func resourceNetworkServicesRegionalMulticastProducerAssociationImport(d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
	config := meta.(*transport_tpg.Config)
	if err := tpgresource.ParseImportId([]string{
		"^projects/(?P<project>[^/]+)/locations/(?P<location>[^/]+)/regionalMulticastProducerAssociations/(?P<regional_multicast_producer_association_id>[^/]+)$",
		"^(?P<project>[^/]+)/(?P<location>[^/]+)/(?P<regional_multicast_producer_association_id>[^/]+)$",
		"^(?P<location>[^/]+)/(?P<regional_multicast_producer_association_id>[^/]+)$",
	}, d, config); err != nil {
		return nil, err
	}

	// Replace import id for the resource id
	id, err := tpgresource.ReplaceVars(d, config, "projects/{{project}}/locations/{{location}}/regionalMulticastProducerAssociations/{{regional_multicast_producer_association_id}}")
	if err != nil {
		return nil, fmt.Errorf("Error constructing id: %s", err)
	}
	d.SetId(id)

	return []*schema.ResourceData{d}, nil
}

func flattenNetworkServicesRegionalMulticastProducerAssociationCreateTime(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenNetworkServicesRegionalMulticastProducerAssociationDescription(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenNetworkServicesRegionalMulticastProducerAssociationLabels(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return v
	}

	transformed := make(map[string]interface{})
	if l, ok := d.GetOkExists("labels"); ok {
		for k := range l.(map[string]interface{}) {
			transformed[k] = v.(map[string]interface{})[k]
		}
	}

	return transformed
}

func flattenNetworkServicesRegionalMulticastProducerAssociationName(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenNetworkServicesRegionalMulticastProducerAssociationNetwork(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenNetworkServicesRegionalMulticastProducerAssociationRegionalMulticastDomainActivation(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenNetworkServicesRegionalMulticastProducerAssociationState(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	original := v.(map[string]interface{})
	if len(original) == 0 {
		return nil
	}
	transformed := make(map[string]interface{})
	transformed["state"] =
		flattenNetworkServicesRegionalMulticastProducerAssociationStateState(original["state"], d, config)
	return []interface{}{transformed}
}
func flattenNetworkServicesRegionalMulticastProducerAssociationStateState(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenNetworkServicesRegionalMulticastProducerAssociationUniqueId(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenNetworkServicesRegionalMulticastProducerAssociationUpdateTime(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenNetworkServicesRegionalMulticastProducerAssociationTerraformLabels(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return v
	}

	transformed := make(map[string]interface{})
	if l, ok := d.GetOkExists("terraform_labels"); ok {
		for k := range l.(map[string]interface{}) {
			transformed[k] = v.(map[string]interface{})[k]
		}
	}

	return transformed
}

func flattenNetworkServicesRegionalMulticastProducerAssociationEffectiveLabels(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func expandNetworkServicesRegionalMulticastProducerAssociationDescription(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandNetworkServicesRegionalMulticastProducerAssociationNetwork(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandNetworkServicesRegionalMulticastProducerAssociationRegionalMulticastDomainActivation(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandNetworkServicesRegionalMulticastProducerAssociationEffectiveLabels(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (map[string]string, error) {
	if v == nil {
		return map[string]string{}, nil
	}
	m := make(map[string]string)
	for k, val := range v.(map[string]interface{}) {
		m[k] = val.(string)
	}
	return m, nil
}

func ResourceNetworkServicesRegionalMulticastProducerAssociationFlatten(d *schema.ResourceData, meta interface{}, res map[string]interface{}, config *transport_tpg.Config, project string, userAgent string, billingProject string, url string, headers http.Header) error {
	var err error

	if err = d.Set("create_time", flattenNetworkServicesRegionalMulticastProducerAssociationCreateTime(res["createTime"], d, config)); err != nil {
		return fmt.Errorf("Error reading RegionalMulticastProducerAssociation: %s", err)
	}
	if err = d.Set("description", flattenNetworkServicesRegionalMulticastProducerAssociationDescription(res["description"], d, config)); err != nil {
		return fmt.Errorf("Error reading RegionalMulticastProducerAssociation: %s", err)
	}
	if err = d.Set("labels", flattenNetworkServicesRegionalMulticastProducerAssociationLabels(res["labels"], d, config)); err != nil {
		return fmt.Errorf("Error reading RegionalMulticastProducerAssociation: %s", err)
	}
	if err = d.Set("name", flattenNetworkServicesRegionalMulticastProducerAssociationName(res["name"], d, config)); err != nil {
		return fmt.Errorf("Error reading RegionalMulticastProducerAssociation: %s", err)
	}
	if err = d.Set("network", flattenNetworkServicesRegionalMulticastProducerAssociationNetwork(res["network"], d, config)); err != nil {
		return fmt.Errorf("Error reading RegionalMulticastProducerAssociation: %s", err)
	}
	if err = d.Set("regional_multicast_domain_activation", flattenNetworkServicesRegionalMulticastProducerAssociationRegionalMulticastDomainActivation(res["regionalMulticastDomainActivation"], d, config)); err != nil {
		return fmt.Errorf("Error reading RegionalMulticastProducerAssociation: %s", err)
	}
	if err = d.Set("state", flattenNetworkServicesRegionalMulticastProducerAssociationState(res["state"], d, config)); err != nil {
		return fmt.Errorf("Error reading RegionalMulticastProducerAssociation: %s", err)
	}
	if err = d.Set("unique_id", flattenNetworkServicesRegionalMulticastProducerAssociationUniqueId(res["uniqueId"], d, config)); err != nil {
		return fmt.Errorf("Error reading RegionalMulticastProducerAssociation: %s", err)
	}
	if err = d.Set("update_time", flattenNetworkServicesRegionalMulticastProducerAssociationUpdateTime(res["updateTime"], d, config)); err != nil {
		return fmt.Errorf("Error reading RegionalMulticastProducerAssociation: %s", err)
	}
	if err = d.Set("terraform_labels", flattenNetworkServicesRegionalMulticastProducerAssociationTerraformLabels(res["labels"], d, config)); err != nil {
		return fmt.Errorf("Error reading RegionalMulticastProducerAssociation: %s", err)
	}
	if err = d.Set("effective_labels", flattenNetworkServicesRegionalMulticastProducerAssociationEffectiveLabels(res["labels"], d, config)); err != nil {
		return fmt.Errorf("Error reading RegionalMulticastProducerAssociation: %s", err)
	}

	return nil
}
