// Copyright IBM Corp. 2014, 2026
// Copyright 2026 Google LLC
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package networkservices_test

import (
	"fmt"
	"log"
	"regexp"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"

	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/acctest"
	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/envvar"
	_ "github.com/hashicorp/terraform-provider-google-nightly/google-nightly/services/compute"
	_ "github.com/hashicorp/terraform-provider-google-nightly/google-nightly/services/networkconnectivityv1"
	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/services/networkservices"
	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/tpgresource"
	transport_tpg "github.com/hashicorp/terraform-provider-google-nightly/google-nightly/transport"

	"google.golang.org/api/googleapi"
)

var (
	_ = fmt.Sprintf
	_ = log.Print
	_ = regexp.MatchString
	_ = strconv.Atoi
	_ = strings.Trim
	_ = time.Now
	_ = resource.TestMain
	_ = terraform.NewState
	_ = envvar.TestEnvVar
	_ = tpgresource.SetLabels
	_ = transport_tpg.Config{}
	_ = googleapi.Error{}
	_ = networkservices.Product
)

func TestAccNetworkServicesRegionalMulticastGroupProducerActivation_networkServicesRegionalMulticastGroupProducerActivationBasicExample(t *testing.T) {
	t.Parallel()

	randomSuffix := acctest.RandString(t, 10)

	context := map[string]interface{}{
		"domain_activation_name":         "tf-test-test-domain-activation-rmgpa" + randomSuffix,
		"domain_name":                    "tf-test-test-domain-rmgpa" + randomSuffix,
		"group_producer_activation_name": "tf-test-test-group-producer-activation-rmgpa" + randomSuffix,
		"group_range_activation_name":    "tf-test-test-group-range-activation-rmgpa" + randomSuffix,
		"group_range_name":               "tf-test-test-group-range-rmgpa" + randomSuffix,
		"internal_range_name":            "tf-test-test-internal-range-rmgpa" + randomSuffix,
		"network_name":                   "tf-test-test-network-rmgpa" + randomSuffix,
		"producer_association_name":      "tf-test-test-producer-association-rmgpa" + randomSuffix,
		"random_suffix":                  randomSuffix,
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderBetaFactories(t),
		CheckDestroy:             testAccCheckNetworkServicesRegionalMulticastGroupProducerActivationDestroyProducer(t),
		Steps: []resource.TestStep{
			{
				Config: testAccNetworkServicesRegionalMulticastGroupProducerActivation_networkServicesRegionalMulticastGroupProducerActivationBasicExample(context),
			},
			{
				ResourceName:            "google_network_services_regional_multicast_group_producer_activation.rmgpa_test",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"labels", "location", "regional_multicast_group_producer_activation_id", "terraform_labels"},
			},
			{
				ResourceName:       "google_network_services_regional_multicast_group_producer_activation.rmgpa_test",
				RefreshState:       true,
				ExpectNonEmptyPlan: true,
				ImportStateKind:    resource.ImportBlockWithResourceIdentity,
			},
		},
	})
}

func testAccNetworkServicesRegionalMulticastGroupProducerActivation_networkServicesRegionalMulticastGroupProducerActivationBasicExample(context map[string]interface{}) string {
	return acctest.Nprintf(`
resource "google_compute_network" "default" {
  name                    = "%{network_name}"
  auto_create_subnetworks = false
}

resource "google_network_services_multicast_domain" "default" {
  multicast_domain_id = "%{domain_name}"
  location            = "global"
  admin_network       = google_compute_network.default.id
}

resource "google_network_services_regional_multicast_domain_activation" "default" {
  regional_multicast_domain_activation_id = "%{domain_activation_name}"
  location                                = "us-central1"
  multicast_domain                        = google_network_services_multicast_domain.default.id
  pim_spec {
    pim_mode                  = "PIM_MODE_SPARSE"
    multicast_source_location = "MULTICAST_SOURCE_GCP"
  }
}

resource "google_network_connectivity_internal_range" "default" {
  name          = "%{internal_range_name}"
  network       = google_compute_network.default.id
  usage         = "FOR_VPC"
  peering       = "FOR_SELF"
  ip_cidr_range = "239.1.1.0/24"
}

resource "google_network_services_multicast_group_range" "default" {
  multicast_group_range_id = "%{group_range_name}"
  location                 = "global"
  multicast_domain         = google_network_services_multicast_domain.default.id
  reserved_internal_range  = google_network_connectivity_internal_range.default.id
}

resource "google_network_services_regional_multicast_group_range_activation" "default" {
  regional_multicast_group_range_activation_id = "%{group_range_activation_name}"
  location                                     = "us-central1"
  multicast_group_range                        = google_network_services_multicast_group_range.default.id
  regional_multicast_domain_activation         = google_network_services_regional_multicast_domain_activation.default.id
}

resource "google_network_services_regional_multicast_producer_association" "default" {
  regional_multicast_producer_association_id = "%{producer_association_name}"
  location                                   = "us-central1"
  network                                    = google_compute_network.default.id
  regional_multicast_domain_activation       = google_network_services_regional_multicast_domain_activation.default.id
}

resource "google_network_services_regional_multicast_group_producer_activation" rmgpa_test {
  regional_multicast_group_producer_activation_id = "%{group_producer_activation_name}"
  location                                      = "us-central1"
  regional_multicast_group_range_activation     = google_network_services_regional_multicast_group_range_activation.default.id
  regional_multicast_producer_association       = google_network_services_regional_multicast_producer_association.default.id
  # Replace with the full resource name of your Interconnect Attachment in the same region
  interconnect_attachments                      = ["projects/123456789/regions/us-central1/interconnectAttachments/test-attachment"]
}
`, context)
}

func testAccCheckNetworkServicesRegionalMulticastGroupProducerActivationDestroyProducer(t *testing.T) func(s *terraform.State) error {
	return func(s *terraform.State) error {
		for name, rs := range s.RootModule().Resources {
			if rs.Type != "google_network_services_regional_multicast_group_producer_activation" {
				continue
			}
			if strings.HasPrefix(name, "data.") {
				continue
			}

			config := acctest.GoogleProviderConfig(t)
			url, err := tpgresource.ReplaceVarsForTest(config, rs, transport_tpg.BaseUrl(networkservices.Product, config)+"projects/{{project}}/locations/{{location}}/regionalMulticastGroupProducerActivations/{{regional_multicast_group_producer_activation_id}}")
			if err != nil {
				return err
			}

			billingProject := ""

			if config.BillingProject != "" {
				billingProject = config.BillingProject
			}

			_, err = transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
				Config:    config,
				Method:    "GET",
				Project:   billingProject,
				RawURL:    url,
				UserAgent: config.UserAgent,
			})
			if err == nil {
				return fmt.Errorf("NetworkServicesRegionalMulticastGroupProducerActivation still exists at %s", url)
			}
		}

		return nil
	}
}
