// Copyright IBM Corp. 2014, 2026
// Copyright 2026 Google LLC
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     *** AUTO GENERATED CODE    *** Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package compute_test

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"

	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/acctest"
	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/envvar"
	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/tpgresource"
)

var (
	_ = fmt.Sprintf
	_ = envvar.TestEnvVar
	_ = tpgresource.SetLabels
)

func TestAccDataSourceComputeHaController_basic(t *testing.T) {
	t.Parallel()

	randomSuffix := acctest.RandString(t, 10)

	context := map[string]interface{}{
		"hac_name":      "tf-test-hac-bs" + randomSuffix,
		"random_suffix": randomSuffix,
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderBetaFactories(t),
		CheckDestroy:             testAccCheckComputeHaControllerDestroyProducer(t),
		Steps: []resource.TestStep{
			{
				Config: testAccComputeHaController_computeHaControllerBasicExampleDataSource(context),
				Check: resource.ComposeTestCheckFunc(
					acctest.CheckDataSourceStateMatchesResourceStateWithIgnores(
						"data.google_compute_ha_controller.default",
						"google_compute_ha_controller.default",
						[]string{
							"region",
						},
					),
				),
			},
		},
	})
}

func testAccComputeHaController_computeHaControllerBasicExampleDataSource(context map[string]interface{}) string {
	return acctest.Nprintf(`
locals {
  region          = "us-central1"
  zone1           = "us-central1-a"
  zone2           = "us-central1-b"
}

data "google_compute_image" "debian_12" {
  provider = google-private
  family   = "debian-12"
  project  = "debian-cloud"
}

resource "google_compute_region_disk" "regional_disk" {
  provider                  = google-private
  name                      = "%{hac_name}-rd"
  physical_block_size_bytes = 4096
  type                      = "pd-balanced"
  region                    = local.region
  replica_zones             = [local.zone1, local.zone2]
  size                      = 10
  image                     = data.google_compute_image.debian_12.self_link
}

resource "google_compute_instance" "vm" {
  provider     = google-private
  name         = "%{hac_name}-inst"
  machine_type = "e2-micro"
  zone         = local.zone1

  boot_disk {
    auto_delete = false
    source      = google_compute_region_disk.regional_disk.self_link
  }

  network_interface {
    network = "default"
  }

  allow_stopping_for_update = true
}

resource "google_compute_ha_controller" "default" {
  provider            = google-private
  name                = "%{hac_name}"
  region              = local.region
  instance_name       = google_compute_instance.vm.name
  failover_initiation = "MANUAL_ONLY"

  zone_configuration {
    zone = local.zone1
  }
  zone_configuration {
    zone = local.zone2
  }
}


data "google_compute_ha_controller" "default" {
  name = google_compute_ha_controller.default.name
}`,
		context,
	)
}
