// Copyright IBM Corp. 2014, 2026
// Copyright 2026 Google LLC
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This code is generated by Magic Modules using the following:
//
//     Configuration: https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/products/compute/HaController.yaml
//     Template:      https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/resource.go.tmpl
//
//     DO NOT EDIT this file directly. Any changes made to this file will be
//     overwritten during the next generation cycle.
//
// ----------------------------------------------------------------------------

package compute

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"reflect"
	"regexp"
	"slices"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/hashicorp/errwrap"
	"github.com/hashicorp/go-cty/cty"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/customdiff"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/id"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/logging"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/retry"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/structure"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	"github.com/hashicorp/terraform-plugin-sdk/v2/terraform"
	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/registry"
	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/tpgresource"
	transport_tpg "github.com/hashicorp/terraform-provider-google-nightly/google-nightly/transport"
	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/verify"

	"google.golang.org/api/googleapi"
)

var (
	_ = bytes.Clone
	_ = context.WithCancel
	_ = base64.NewDecoder
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = log.Print
	_ = http.Get
	_ = reflect.ValueOf
	_ = regexp.Match
	_ = slices.Min([]int{1})
	_ = sort.IntSlice{}
	_ = strconv.Atoi
	_ = strings.Trim
	_ = time.Now
	_ = errwrap.Wrap
	_ = cty.BoolVal
	_ = diag.Diagnostic{}
	_ = customdiff.All
	_ = id.UniqueId
	_ = logging.LogLevel
	_ = retry.Retry
	_ = schema.Noop
	_ = validation.All
	_ = structure.ExpandJsonFromString
	_ = terraform.State{}
	_ = tpgresource.SetLabels
	_ = transport_tpg.Config{}
	_ = verify.ValidateEnum
	_ = googleapi.Error{}
)

func init() {
	registry.Schema{
		Name:        "google_compute_ha_controller",
		ProductName: "compute",
		Type:        registry.SchemaTypeResource,
		Schema:      ResourceComputeHaController(),
	}.Register()
}

func ResourceComputeHaController() *schema.Resource {
	return &schema.Resource{
		Create: resourceComputeHaControllerCreate,
		Read:   resourceComputeHaControllerRead,
		Update: resourceComputeHaControllerUpdate,
		Delete: resourceComputeHaControllerDelete,

		Importer: &schema.ResourceImporter{
			State: resourceComputeHaControllerImport,
		},

		Timeouts: &schema.ResourceTimeout{
			Create: schema.DefaultTimeout(20 * time.Minute),
			Delete: schema.DefaultTimeout(20 * time.Minute),
		},

		CustomizeDiff: customdiff.All(
			tpgresource.DefaultProviderProject,
			tpgresource.DefaultProviderDeletionPolicy("DELETE"),
		),

		Identity: &schema.ResourceIdentity{
			Version: 1,
			SchemaFunc: func() map[string]*schema.Schema {
				return map[string]*schema.Schema{
					"name": {
						Type:              schema.TypeString,
						RequiredForImport: true,
					},
					"region": {
						Type:              schema.TypeString,
						RequiredForImport: true,
					},
					"project": {
						Type:              schema.TypeString,
						OptionalForImport: true,
					},
				}
			},
		},
		ResourceBehavior: schema.ResourceBehavior{
			MutableIdentity: true,
		},

		Schema: map[string]*schema.Schema{
			"instance_name": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
				Description: `Name of the instance that HaController is in charge of.
Must comply with RFC1035. Instance must exist in one of two provided zones.`,
			},
			"name": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
				Description: `Name of the resource.
The name must be 1-63 characters long, and comply with RFC1035.`,
			},
			"region": {
				Type:             schema.TypeString,
				Computed:         true,
				Optional:         true,
				ForceNew:         true,
				DiffSuppressFunc: tpgresource.CompareSelfLinkOrResourceName,
				Description:      `The region where the HA Controller will be created.`,
			},
			"zone_configuration": {
				Type:        schema.TypeSet,
				Required:    true,
				ForceNew:    true,
				Description: `Set of 2 distinct zones configurations.`,
				MinItems:    2,
				MaxItems:    2,
				Elem:        computeHaControllerZoneConfigurationSchema(),
				// Default schema.HashSchema is used.
			},
			"backend_services": {
				Type:     schema.TypeList,
				Computed: true,
				Optional: true,
				ForceNew: true,
				Description: `Currently, only one backend service can be specified,
and it must be for an L4 Internal Load Balancer (ILB).
Provide the full URL of the backend service.`,
				Elem: &schema.Schema{
					Type: schema.TypeString,
				},
			},
			"description": {
				Type:     schema.TypeString,
				Optional: true,
				ForceNew: true,
				Description: `A description of this resource.
Maximum length of 2048 characters.`,
			},
			"failover_initiation": {
				Type:         schema.TypeString,
				Optional:     true,
				ForceNew:     true,
				ValidateFunc: verify.ValidateEnum([]string{"AUTOMATIC", "MANUAL_ONLY", ""}),
				Description: `Indicates how failover should be initiated.
Possible values are:
- "AUTOMATIC": Automatically detect zonal outages and perform failover.
- "MANUAL_ONLY": Failover is not initiated automatically, a user has to perform it manually. Possible values: ["AUTOMATIC", "MANUAL_ONLY"]`,
			},
			"networking_auto_configuration": {
				Type:     schema.TypeList,
				Computed: true,
				Optional: true,
				ForceNew: true,
				Description: `Basic networking configuration. Required backend services and
forwarding rules will be automatically created with default parameters.`,
				MaxItems: 1,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"internal": {
							Type:        schema.TypeList,
							Computed:    true,
							Optional:    true,
							ForceNew:    true,
							Description: `Internal networking configuration.`,
							MaxItems:    1,
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"ip_address": {
										Type:     schema.TypeString,
										Computed: true,
										Optional: true,
										ForceNew: true,
										Description: `IP addresses will be automatically allocated according to
StackType if not provided.`,
									},
									"ipv6_address": {
										Type:     schema.TypeString,
										Computed: true,
										Optional: true,
										ForceNew: true,
										Description: `IP addresses will be automatically allocated according to
StackType if not provided.`,
									},
									"stack_type": {
										Type:         schema.TypeString,
										Computed:     true,
										Optional:     true,
										ForceNew:     true,
										ValidateFunc: verify.ValidateEnum([]string{"IPV4_ONLY", "IPV4_IPV6", "IPV6_ONLY", ""}),
										Description: `Determine which IP addresses to automatically create.
Possible values:
- "IPV4_ONLY": Assign IPv4 address only.
- "IPV4_IPV6": Assign both IPv4 and IPv6 addresses.
- "IPV6_ONLY": Assign IPv6 address only. Possible values: ["IPV4_ONLY", "IPV4_IPV6", "IPV6_ONLY"]`,
									},
								},
							},
						},
					},
				},
			},
			"project": {
				Type:     schema.TypeString,
				Optional: true,
				Computed: true,
				ForceNew: true,
			},
			"self_link": {
				Type:     schema.TypeString,
				Computed: true,
			},
			"deletion_policy": {
				Type:     schema.TypeString,
				Optional: true,
				Computed: true,
				Description: `Whether Terraform will be prevented from destroying the instance. Defaults to "DELETE".
When a 'terraform destroy' or 'terraform apply' would delete the instance,
the command will fail if this field is set to "PREVENT" in Terraform state.
When set to "ABANDON", the command will remove the resource from Terraform
management without updating or deleting the resource in the API.
When set to "DELETE", deleting the resource is allowed.
`,
			},
		},
		UseJSONNumber: true,
	}
}

func computeHaControllerZoneConfigurationSchema() *schema.Resource {
	return &schema.Resource{
		Schema: map[string]*schema.Schema{
			"zone": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: `Required, should be unique for every set item.`,
			},
			"node_affinities": {
				Type:     schema.TypeList,
				Optional: true,
				ForceNew: true,
				Description: `Specifies node affinities or anti-affinities to determine
which sole-tenant nodes your instances and managed instance groups
will use as host systems`,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"key": {
							Type:        schema.TypeString,
							Optional:    true,
							ForceNew:    true,
							Description: `The key for the node affinity label.`,
						},
						"operator": {
							Type:         schema.TypeString,
							Optional:     true,
							ForceNew:     true,
							ValidateFunc: verify.ValidateEnum([]string{"IN", "NOT_IN", ""}),
							Description: `Defines the operation of node selection.
Possible values:
- "IN": Requires Compute Engine to seek for matched nodes.
- "NOT_IN": Requires Compute Engine to avoid certain nodes. Possible values: ["IN", "NOT_IN"]`,
						},
						"values": {
							Type:        schema.TypeList,
							Optional:    true,
							ForceNew:    true,
							Description: `Corresponds to the label values of Node resource.`,
							Elem: &schema.Schema{
								Type: schema.TypeString,
							},
						},
					},
				},
			},
			"reservation_affinity": {
				Type:        schema.TypeList,
				Optional:    true,
				ForceNew:    true,
				Description: `A nested object resource.`,
				MaxItems:    1,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"specific_reservation": {
							Type:        schema.TypeList,
							Optional:    true,
							ForceNew:    true,
							Description: `Required when type is SPECIFIC_RESERVATION`,
							MaxItems:    1,
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"key": {
										Type:     schema.TypeString,
										Optional: true,
										ForceNew: true,
										Description: `The key for the reservation. To target a SPECIFIC_RESERVATION by name,
use "compute.googleapis.com/reservation-name".`,
									},
									"values": {
										Type:     schema.TypeList,
										Optional: true,
										ForceNew: true,
										Description: `The values for the reservation. Typically the name of the reservation.
For shared reservations, use the format
"projects/different-project/reservations/some-reservation-name".
Limited to a single value.`,
										Elem: &schema.Schema{
											Type: schema.TypeString,
										},
									},
								},
							},
						},
						"type": {
							Type:         schema.TypeString,
							Optional:     true,
							ForceNew:     true,
							ValidateFunc: verify.ValidateEnum([]string{"NO_RESERVATION", "ANY_RESERVATION", "SPECIFIC_RESERVATION", "SPECIFIC_THEN_ANY_RESERVATION", "SPECIFIC_THEN_NO_RESERVATION", "ANY_RESERVATION_THEN_FAIL", ""}),
							Description: `Specifies the type of reservation from which this instance can consume resources. Possible values:
- "NO_RESERVATION": Do not consume from any allocated capacity.
- "ANY_RESERVATION": Consume any allocation available.
- "SPECIFIC_RESERVATION": Must consume from a specific reservation (key and values must be set).
- "SPECIFIC_THEN_ANY_RESERVATION": Prefer specific, fallback to any.
- "SPECIFIC_THEN_NO_RESERVATION": Prefer specific, fallback to on-demand.
- "ANY_RESERVATION_THEN_FAIL": Consume any, fail if none. Possible values: ["NO_RESERVATION", "ANY_RESERVATION", "SPECIFIC_RESERVATION", "SPECIFIC_THEN_ANY_RESERVATION", "SPECIFIC_THEN_NO_RESERVATION", "ANY_RESERVATION_THEN_FAIL"]`,
						},
					},
				},
			},
		},
	}
}

func resourceComputeHaControllerCreate(d *schema.ResourceData, meta interface{}) error {
	config := meta.(*transport_tpg.Config)
	userAgent, err := tpgresource.GenerateUserAgentString(d, config.UserAgent)
	if err != nil {
		return err
	}

	obj := make(map[string]interface{})
	nameProp, err := expandComputeHaControllerName(d.Get("name"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("name"); !tpgresource.IsEmptyValue(reflect.ValueOf(nameProp)) && (ok || !reflect.DeepEqual(v, nameProp)) {
		obj["name"] = nameProp
	}
	descriptionProp, err := expandComputeHaControllerDescription(d.Get("description"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("description"); !tpgresource.IsEmptyValue(reflect.ValueOf(descriptionProp)) && (ok || !reflect.DeepEqual(v, descriptionProp)) {
		obj["description"] = descriptionProp
	}
	instanceNameProp, err := expandComputeHaControllerInstanceName(d.Get("instance_name"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("instance_name"); !tpgresource.IsEmptyValue(reflect.ValueOf(instanceNameProp)) && (ok || !reflect.DeepEqual(v, instanceNameProp)) {
		obj["instanceName"] = instanceNameProp
	}
	failoverInitiationProp, err := expandComputeHaControllerFailoverInitiation(d.Get("failover_initiation"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("failover_initiation"); !tpgresource.IsEmptyValue(reflect.ValueOf(failoverInitiationProp)) && (ok || !reflect.DeepEqual(v, failoverInitiationProp)) {
		obj["failoverInitiation"] = failoverInitiationProp
	}
	zoneConfigurationProp, err := expandComputeHaControllerZoneConfiguration(d.Get("zone_configuration"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("zone_configuration"); !tpgresource.IsEmptyValue(reflect.ValueOf(zoneConfigurationProp)) && (ok || !reflect.DeepEqual(v, zoneConfigurationProp)) {
		obj["zoneConfigurations"] = zoneConfigurationProp
	}
	networkingAutoConfigurationProp, err := expandComputeHaControllerNetworkingAutoConfiguration(d.Get("networking_auto_configuration"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("networking_auto_configuration"); !tpgresource.IsEmptyValue(reflect.ValueOf(networkingAutoConfigurationProp)) && (ok || !reflect.DeepEqual(v, networkingAutoConfigurationProp)) {
		obj["networkingAutoConfiguration"] = networkingAutoConfigurationProp
	}
	backendServicesProp, err := expandComputeHaControllerBackendServices(d.Get("backend_services"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("backend_services"); !tpgresource.IsEmptyValue(reflect.ValueOf(backendServicesProp)) && (ok || !reflect.DeepEqual(v, backendServicesProp)) {
		obj["backendServices"] = backendServicesProp
	}
	regionProp, err := expandComputeHaControllerRegion(d.Get("region"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("region"); !tpgresource.IsEmptyValue(reflect.ValueOf(regionProp)) && (ok || !reflect.DeepEqual(v, regionProp)) {
		obj["region"] = regionProp
	}

	url, err := tpgresource.ReplaceVars(d, config, transport_tpg.BaseUrl(Product, config)+"projects/{{project}}/regions/{{region}}/haControllers")
	if err != nil {
		return err
	}

	log.Printf("[DEBUG] Creating new HaController: %#v", obj)
	billingProject := ""

	project, err := tpgresource.GetProject(d, config)
	if err != nil {
		return fmt.Errorf("Error fetching project for HaController: %s", err)
	}
	billingProject = project

	// err == nil indicates that the billing_project value was found
	if bp, err := tpgresource.GetBillingProject(d, config); err == nil {
		billingProject = bp
	}

	headers := make(http.Header)
	res, err := transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
		Config:    config,
		Method:    "POST",
		Project:   billingProject,
		RawURL:    url,
		UserAgent: userAgent,
		Body:      obj,
		Timeout:   d.Timeout(schema.TimeoutCreate),
		Headers:   headers,
	})
	if err != nil {
		return fmt.Errorf("Error creating HaController: %s", err)
	}

	// Store the ID now
	id, err := tpgresource.ReplaceVars(d, config, "projects/{{project}}/regions/{{region}}/haControllers/{{name}}")
	if err != nil {
		return fmt.Errorf("Error constructing id: %s", err)
	}
	d.SetId(id)

	err = ComputeOperationWaitTime(
		config, res, project, "Creating HaController", userAgent,
		d.Timeout(schema.TimeoutCreate))

	if err != nil {
		// The resource didn't actually create
		d.SetId("")
		return fmt.Errorf("Error waiting to create HaController: %s", err)
	}

	log.Printf("[DEBUG] Finished creating HaController %q: %#v", d.Id(), res)

	identity, err := d.Identity()
	if err == nil && identity != nil {
		if nameValue, ok := d.GetOk("name"); ok && nameValue.(string) != "" {
			if err = identity.Set("name", nameValue.(string)); err != nil {
				return fmt.Errorf("Error setting name: %s", err)
			}
		}
		if regionValue, ok := d.GetOk("region"); ok && regionValue.(string) != "" {
			if err = identity.Set("region", regionValue.(string)); err != nil {
				return fmt.Errorf("Error setting region: %s", err)
			}
		}
		if projectValue, ok := d.GetOk("project"); ok && projectValue.(string) != "" {
			if err = identity.Set("project", projectValue.(string)); err != nil {
				return fmt.Errorf("Error setting project: %s", err)
			}
		}
	} else {
		log.Printf("[DEBUG] (Create) identity not set: %s", err)
	}

	return resourceComputeHaControllerRead(d, meta)
}

func resourceComputeHaControllerRead(d *schema.ResourceData, meta interface{}) error {
	config := meta.(*transport_tpg.Config)
	userAgent, err := tpgresource.GenerateUserAgentString(d, config.UserAgent)
	if err != nil {
		return err
	}

	url, err := tpgresource.ReplaceVars(d, config, transport_tpg.BaseUrl(Product, config)+"projects/{{project}}/regions/{{region}}/haControllers/{{name}}")
	if err != nil {
		return err
	}

	billingProject := ""

	project, err := tpgresource.GetProject(d, config)
	if err != nil {
		return fmt.Errorf("Error fetching project for HaController: %s", err)
	}
	billingProject = project

	// err == nil indicates that the billing_project value was found
	if bp, err := tpgresource.GetBillingProject(d, config); err == nil {
		billingProject = bp
	}

	headers := make(http.Header)
	res, err := transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
		Config:    config,
		Method:    "GET",
		Project:   billingProject,
		RawURL:    url,
		UserAgent: userAgent,
		Headers:   headers,
	})
	if err != nil {
		return transport_tpg.HandleNotFoundError(err, d, fmt.Sprintf("ComputeHaController %q", d.Id()))
	}

	log.Printf("[DEBUG] Finished reading ComputeHaController %q: %#v", d.Id(), res)

	// Explicitly set virtual fields to default values if unset
	if _, ok := d.GetOkExists("deletion_policy"); !ok {
		//prioritize config's value if present
		if config.DeletionPolicy != "" {
			if err := d.Set("deletion_policy", config.DeletionPolicy); err != nil {
				return fmt.Errorf("Error setting deletion_policy: %s", err)
			}
		} else {
			if err := d.Set("deletion_policy", "DELETE"); err != nil {
				return fmt.Errorf("Error setting deletion_policy: %s", err)
			}
		}
	}
	if err := d.Set("project", project); err != nil {
		return fmt.Errorf("Error reading HaController: %s", err)
	}

	err = ResourceComputeHaControllerFlatten(d, meta, res, config, project, userAgent, billingProject, url, headers)
	if err != nil {
		return err
	}

	identity, err := d.Identity()
	if err == nil && identity != nil {
		if v, ok := identity.GetOk("name"); !ok && v == "" {
			err = identity.Set("name", d.Get("name").(string))
			if err != nil {
				return fmt.Errorf("Error setting name: %s", err)
			}
		}
		if v, ok := identity.GetOk("region"); !ok && v == "" {
			err = identity.Set("region", d.Get("region").(string))
			if err != nil {
				return fmt.Errorf("Error setting region: %s", err)
			}
		}
		if v, ok := identity.GetOk("project"); !ok && v == "" {
			err = identity.Set("project", d.Get("project").(string))
			if err != nil {
				return fmt.Errorf("Error setting project: %s", err)
			}
		}
	} else {
		log.Printf("[DEBUG] (Read) identity not set: %s", err)
	}

	return nil
}

func resourceComputeHaControllerUpdate(d *schema.ResourceData, meta interface{}) error {
	// Only the root field "deletion_policy", "labels", "terraform_labels", and virtual fields are mutable
	return resourceComputeHaControllerRead(d, meta)
}

func resourceComputeHaControllerDelete(d *schema.ResourceData, meta interface{}) error {
	if d.Get("deletion_policy").(string) == "PREVENT" {
		return fmt.Errorf("cannot destroy ComputeHaController without setting deletion_policy=\"DELETE\" and running `terraform apply`")
	}
	if d.Get("deletion_policy").(string) == "ABANDON" {
		log.Printf("[DEBUG] deletion_policy set to \"ABANDON\", removing HaController %q from Terraform state without deletion", d.Id())
		return nil
	}
	config := meta.(*transport_tpg.Config)
	userAgent, err := tpgresource.GenerateUserAgentString(d, config.UserAgent)
	if err != nil {
		return err
	}

	billingProject := ""

	project, err := tpgresource.GetProject(d, config)
	if err != nil {
		return fmt.Errorf("Error fetching project for HaController: %s", err)
	}
	billingProject = project
	url, err := tpgresource.ReplaceVars(d, config, transport_tpg.BaseUrl(Product, config)+"projects/{{project}}/regions/{{region}}/haControllers/{{name}}")
	if err != nil {
		return err
	}

	var obj map[string]interface{}

	// err == nil indicates that the billing_project value was found
	if bp, err := tpgresource.GetBillingProject(d, config); err == nil {
		billingProject = bp
	}

	headers := make(http.Header)

	log.Printf("[DEBUG] Deleting HaController %q", d.Id())
	res, err := transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
		Config:    config,
		Method:    "DELETE",
		Project:   billingProject,
		RawURL:    url,
		UserAgent: userAgent,
		Body:      obj,
		Timeout:   d.Timeout(schema.TimeoutDelete),
		Headers:   headers,
	})
	if err != nil {
		return transport_tpg.HandleNotFoundError(err, d, "HaController")
	}

	err = ComputeOperationWaitTime(
		config, res, project, "Deleting HaController", userAgent,
		d.Timeout(schema.TimeoutDelete))

	if err != nil {
		return err
	}

	log.Printf("[DEBUG] Finished deleting HaController %q: %#v", d.Id(), res)
	return nil
}

func resourceComputeHaControllerImport(d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
	config := meta.(*transport_tpg.Config)
	if err := tpgresource.ParseImportId([]string{
		"^projects/(?P<project>[^/]+)/regions/(?P<region>[^/]+)/haControllers/(?P<name>[^/]+)$",
		"^(?P<project>[^/]+)/(?P<region>[^/]+)/(?P<name>[^/]+)$",
		"^(?P<region>[^/]+)/(?P<name>[^/]+)$",
		"^(?P<name>[^/]+)$",
	}, d, config); err != nil {
		return nil, err
	}

	// Replace import id for the resource id
	id, err := tpgresource.ReplaceVars(d, config, "projects/{{project}}/regions/{{region}}/haControllers/{{name}}")
	if err != nil {
		return nil, fmt.Errorf("Error constructing id: %s", err)
	}
	d.SetId(id)

	return []*schema.ResourceData{d}, nil
}

func flattenComputeHaControllerName(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenComputeHaControllerDescription(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenComputeHaControllerInstanceName(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenComputeHaControllerFailoverInitiation(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenComputeHaControllerZoneConfiguration(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	original := v.(map[string]interface{})
	transformed := make([]interface{}, 0, len(original))

	for zone, rawConfig := range original {
		if rawConfig == nil {
			continue
		}
		configMap := rawConfig.(map[string]interface{})
		item := make(map[string]interface{})
		item["zone"] = zone

		if resAffRaw, ok := configMap["reservationAffinity"]; ok && resAffRaw != nil {
			if transformedResAff := flattenReservationAffinity(resAffRaw.(map[string]interface{})); transformedResAff != nil {
				item["reservation_affinity"] = transformedResAff
			}
		}

		if nodeAffRaw, ok := configMap["nodeAffinities"]; ok {
			if transformedNodeAffs := flattenComputeHaControllerZoneConfigurationNodeAffinities(nodeAffRaw); len(transformedNodeAffs) > 0 {
				item["node_affinities"] = transformedNodeAffs
			}
		}

		transformed = append(transformed, item)
	}

	return transformed
}

func flattenComputeHaControllerZoneConfigurationNodeAffinities(raw interface{}) []interface{} {
	if raw == nil {
		return nil
	}
	nodeAffList, ok := raw.([]interface{})
	if !ok {
		return nil
	}
	var transformed []interface{}
	for _, rawNodeAff := range nodeAffList {
		if rawNodeAff == nil {
			continue
		}
		nodeAff := rawNodeAff.(map[string]interface{})
		transformedNodeAff := make(map[string]interface{})

		if val, ok := nodeAff["key"]; ok && val != nil {
			transformedNodeAff["key"] = val
		}
		if val, ok := nodeAff["operator"]; ok && val != nil {
			transformedNodeAff["operator"] = val
		}
		if val, ok := nodeAff["values"]; ok && val != nil {
			transformedNodeAff["values"] = val
		}
		transformed = append(transformed, transformedNodeAff)
	}
	return transformed
}

func flattenComputeHaControllerNetworkingAutoConfiguration(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	original := v.(map[string]interface{})
	if len(original) == 0 {
		return nil
	}
	transformed := make(map[string]interface{})
	transformed["internal"] =
		flattenComputeHaControllerNetworkingAutoConfigurationInternal(original["internal"], d, config)
	return []interface{}{transformed}
}
func flattenComputeHaControllerNetworkingAutoConfigurationInternal(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	original := v.(map[string]interface{})
	if len(original) == 0 {
		return nil
	}
	transformed := make(map[string]interface{})
	transformed["stack_type"] =
		flattenComputeHaControllerNetworkingAutoConfigurationInternalStackType(original["stackType"], d, config)
	transformed["ip_address"] =
		flattenComputeHaControllerNetworkingAutoConfigurationInternalIpAddress(original["ipAddress"], d, config)
	transformed["ipv6_address"] =
		flattenComputeHaControllerNetworkingAutoConfigurationInternalIpv6Address(original["ipv6Address"], d, config)
	return []interface{}{transformed}
}
func flattenComputeHaControllerNetworkingAutoConfigurationInternalStackType(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenComputeHaControllerNetworkingAutoConfigurationInternalIpAddress(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenComputeHaControllerNetworkingAutoConfigurationInternalIpv6Address(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenComputeHaControllerBackendServices(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenComputeHaControllerRegion(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return v
	}
	return tpgresource.ConvertSelfLinkToV1(v.(string))
}

func expandComputeHaControllerName(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandComputeHaControllerDescription(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandComputeHaControllerInstanceName(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandComputeHaControllerFailoverInitiation(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandComputeHaControllerZoneConfiguration(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	if v == nil {
		return nil, nil
	}
	transformed := make(map[string]interface{})
	var l []interface{}
	if sdkSet, ok := v.(*schema.Set); ok {
		l = sdkSet.List()
	} else if slice, ok := v.([]interface{}); ok {
		l = slice
	} else {
		return nil, fmt.Errorf("unexpected type to expand: %T", v)
	}

	for _, rawItem := range l {
		if rawItem == nil {
			continue
		}
		item := rawItem.(map[string]interface{})
		zoneVal, ok := item["zone"]
		if !ok || zoneVal == nil || zoneVal.(string) == "" {
			continue
		}
		zone := zoneVal.(string)

		transformedItem := make(map[string]interface{})

		if resAff, ok := item["reservation_affinity"]; ok {
			if expanded := expandComputeHaControllerZoneConfigurationReservationAffinity(resAff); expanded != nil {
				transformedItem["reservationAffinity"] = expanded
			}
		}

		if nodeAff, ok := item["node_affinities"]; ok {
			if expanded := expandComputeHaControllerZoneConfigurationNodeAffinities(nodeAff); len(expanded) > 0 {
				transformedItem["nodeAffinities"] = expanded
			}
		}

		transformed[zone] = transformedItem
	}

	return transformed, nil
}

func expandComputeHaControllerZoneConfigurationReservationAffinity(raw interface{}) interface{} {
	if raw == nil {
		return nil
	}
	list, ok := raw.([]interface{})
	if !ok || len(list) == 0 || list[0] == nil {
		return nil
	}
	resAff := list[0].(map[string]interface{})
	transformed := make(map[string]interface{})

	if val, ok := resAff["type"]; ok && val != nil {
		transformed["consumeReservationType"] = val
	}

	if specResRaw, ok := resAff["specific_reservation"]; ok && specResRaw != nil {
		specResList, _ := specResRaw.([]interface{})
		if len(specResList) > 0 && specResList[0] != nil {
			specRes := specResList[0].(map[string]interface{})
			if val, ok := specRes["key"]; ok && val != nil {
				transformed["key"] = val
			}
			if val, ok := specRes["values"]; ok && val != nil {
				transformed["values"] = val
			}
		}
	}
	return transformed
}

func expandComputeHaControllerZoneConfigurationNodeAffinities(raw interface{}) []interface{} {
	if raw == nil {
		return nil
	}
	var list []interface{}
	if sdkSet, ok := raw.(*schema.Set); ok {
		list = sdkSet.List()
	} else if slice, ok := raw.([]interface{}); ok {
		list = slice
	} else {
		return nil
	}

	var transformed []interface{}
	for _, rawItem := range list {
		if rawItem == nil {
			continue
		}
		nodeAff := rawItem.(map[string]interface{})
		transformedItem := make(map[string]interface{})

		if val, ok := nodeAff["key"]; ok && val != nil {
			transformedItem["key"] = val
		}
		if val, ok := nodeAff["operator"]; ok && val != nil {
			transformedItem["operator"] = val
		}
		if val, ok := nodeAff["values"]; ok && val != nil {
			transformedItem["values"] = val
		}
		transformed = append(transformed, transformedItem)
	}
	return transformed
}

func expandComputeHaControllerNetworkingAutoConfiguration(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	if v == nil {
		return nil, nil
	}
	l := v.([]interface{})
	if len(l) == 0 || l[0] == nil {
		return nil, nil
	}
	raw := l[0]
	original := raw.(map[string]interface{})
	transformed := make(map[string]interface{})

	transformedInternal, err := expandComputeHaControllerNetworkingAutoConfigurationInternal(original["internal"], d, config)
	if err != nil {
		return nil, err
	} else if val := reflect.ValueOf(transformedInternal); val.IsValid() && !tpgresource.IsEmptyValue(val) {
		transformed["internal"] = transformedInternal
	}

	return transformed, nil
}

func expandComputeHaControllerNetworkingAutoConfigurationInternal(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	if v == nil {
		return nil, nil
	}
	l := v.([]interface{})
	if len(l) == 0 || l[0] == nil {
		return nil, nil
	}
	raw := l[0]
	original := raw.(map[string]interface{})
	transformed := make(map[string]interface{})

	transformedStackType, err := expandComputeHaControllerNetworkingAutoConfigurationInternalStackType(original["stack_type"], d, config)
	if err != nil {
		return nil, err
	} else if val := reflect.ValueOf(transformedStackType); val.IsValid() && !tpgresource.IsEmptyValue(val) {
		transformed["stackType"] = transformedStackType
	}

	transformedIpAddress, err := expandComputeHaControllerNetworkingAutoConfigurationInternalIpAddress(original["ip_address"], d, config)
	if err != nil {
		return nil, err
	} else if val := reflect.ValueOf(transformedIpAddress); val.IsValid() && !tpgresource.IsEmptyValue(val) {
		transformed["ipAddress"] = transformedIpAddress
	}

	transformedIpv6Address, err := expandComputeHaControllerNetworkingAutoConfigurationInternalIpv6Address(original["ipv6_address"], d, config)
	if err != nil {
		return nil, err
	} else if val := reflect.ValueOf(transformedIpv6Address); val.IsValid() && !tpgresource.IsEmptyValue(val) {
		transformed["ipv6Address"] = transformedIpv6Address
	}

	return transformed, nil
}

func expandComputeHaControllerNetworkingAutoConfigurationInternalStackType(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandComputeHaControllerNetworkingAutoConfigurationInternalIpAddress(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandComputeHaControllerNetworkingAutoConfigurationInternalIpv6Address(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandComputeHaControllerBackendServices(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandComputeHaControllerRegion(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func ResourceComputeHaControllerFlatten(d *schema.ResourceData, meta interface{}, res map[string]interface{}, config *transport_tpg.Config, project string, userAgent string, billingProject string, url string, headers http.Header) error {
	var err error

	if err = d.Set("name", flattenComputeHaControllerName(res["name"], d, config)); err != nil {
		return fmt.Errorf("Error reading HaController: %s", err)
	}
	if err = d.Set("description", flattenComputeHaControllerDescription(res["description"], d, config)); err != nil {
		return fmt.Errorf("Error reading HaController: %s", err)
	}
	if err = d.Set("instance_name", flattenComputeHaControllerInstanceName(res["instanceName"], d, config)); err != nil {
		return fmt.Errorf("Error reading HaController: %s", err)
	}
	if err = d.Set("failover_initiation", flattenComputeHaControllerFailoverInitiation(res["failoverInitiation"], d, config)); err != nil {
		return fmt.Errorf("Error reading HaController: %s", err)
	}
	if err = d.Set("zone_configuration", flattenComputeHaControllerZoneConfiguration(res["zoneConfigurations"], d, config)); err != nil {
		return fmt.Errorf("Error reading HaController: %s", err)
	}
	if err = d.Set("networking_auto_configuration", flattenComputeHaControllerNetworkingAutoConfiguration(res["networkingAutoConfiguration"], d, config)); err != nil {
		return fmt.Errorf("Error reading HaController: %s", err)
	}
	if err = d.Set("backend_services", flattenComputeHaControllerBackendServices(res["backendServices"], d, config)); err != nil {
		return fmt.Errorf("Error reading HaController: %s", err)
	}
	if err = d.Set("region", flattenComputeHaControllerRegion(res["region"], d, config)); err != nil {
		return fmt.Errorf("Error reading HaController: %s", err)
	}
	if selfLink, ok := res["selfLink"].(string); ok && selfLink != "" {
		if err = d.Set("self_link", tpgresource.ConvertSelfLinkToV1(selfLink)); err != nil {
			return fmt.Errorf("Error reading HaController: %s", err)
		}
	}
	return nil
}
