// Copyright IBM Corp. 2014, 2026
// Copyright 2026 Google LLC
// SPDX-License-Identifier: MPL-2.0
// ----------------------------------------------------------------------------
//
//	***     AUTO GENERATED CODE    ***    Type: Handwritten     ***
//
// ----------------------------------------------------------------------------
//
//	This code is generated by Magic Modules using the following:
//
//	Source file: https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/services/compute/resource_compute_ha_controller_test.go
//
//	DO NOT EDIT this file directly. Any changes made to this file will be
//	overwritten during the next generation cycle.
//
// ----------------------------------------------------------------------------
package compute_test

import (
	"fmt"
	"os"
	"testing"
	"time"

	transport_tpg "github.com/hashicorp/terraform-provider-google-nightly/google-nightly/transport"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/plancheck"

	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/acctest"
	tpgcompute "github.com/hashicorp/terraform-provider-google-nightly/google-nightly/services/compute"
	_ "github.com/hashicorp/terraform-provider-google-nightly/google-nightly/services/tags"
)

func TestAccComputeHaController_failoverThenDelete_noDiff(t *testing.T) {
	t.Parallel()
	os.Setenv("TF_COMPUTE_INSTANCE_DISABLE_MULTIPLE_ZONE_CHECK", "1")

	zone1 := "us-central1-a"
	zone2 := "us-central1-b"
	region := "us-central1"

	hacName := fmt.Sprintf("tf-test-%s", acctest.RandString(t, 10))
	context := map[string]interface{}{
		"hac_name": hacName,
		"zone1":    zone1,
		"zone2":    zone2,
		"region":   region,
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactories(t),
		Steps: []resource.TestStep{
			{
				Config: testAccHaController_basic(context),
			},
			{
				PreConfig: func() {
					config := acctest.GoogleProviderConfig(t)

					url := fmt.Sprintf("%sprojects/%s/regions/%s/haControllers/%s",
						transport_tpg.BaseUrl(tpgcompute.Product, config), config.Project, region, hacName)

					res, err := transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
						Config:    config,
						Method:    "GET",
						Project:   config.Project,
						RawURL:    url,
						UserAgent: config.UserAgent,
					})
					if err != nil {
						t.Fatalf("Failed to GET HaController %s: %v", hacName, err)
					}

					var primaryZone string
					if status, ok := res["status"].(map[string]interface{}); ok {
						if pZone, ok := status["primaryZone"].(string); ok {
							primaryZone = pZone
						}
					}

					var targetZone string
					if primaryZone == zone1 {
						targetZone = zone2
					} else {
						targetZone = zone1
					}

					req := map[string]interface{}{
						"failoverToZone": targetZone,
					}

					failoverUrl := fmt.Sprintf("%sprojects/%s/regions/%s/haControllers/%s/failover",
						transport_tpg.BaseUrl(tpgcompute.Product, config), config.Project, region, hacName)

					op, err := transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
						Config:    config,
						Method:    "POST",
						Project:   config.Project,
						RawURL:    failoverUrl,
						UserAgent: config.UserAgent,
						Body:      req,
					})
					if err != nil {
						t.Fatalf("Failed to trigger failover for HaController %s: %v", hacName, err)
					}

					if waitErr := tpgcompute.ComputeOperationWaitTime(config, op, config.Project, "waiting failover to finish", config.UserAgent, 10*time.Minute); waitErr != nil {
						t.Fatalf("Error waiting for failover: %s", waitErr)
					}
				},
				Config: testAccHaController_noHac(context),
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction("google_compute_instance.vm", plancheck.ResourceActionNoop),
					},
				},
			},
			{
				Config:             testAccHaController_noHac(context),
				ExpectNonEmptyPlan: false,
			},
		},
	})
}

func testAccHaController_basic(context map[string]interface{}) string {
	return acctest.Nprintf(`
data "google_compute_image" "debian_12" {
  family   = "debian-12"
  project  = "debian-cloud"
}

resource "google_compute_region_disk" "regional_disk" {
  name                      = "%{hac_name}-rd"
  physical_block_size_bytes = 4096
  type                      = "pd-balanced"
  region                    = "%{region}"
  replica_zones             = ["%{zone1}", "%{zone2}"]
  size                      = 15
  image                     = data.google_compute_image.debian_12.self_link
}

resource "google_compute_instance" "vm" {
  name         = "%{hac_name}-inst"
  machine_type = "e2-micro"
  zones {
    zone = "%{zone1}"
  }
  zones {
    zone = "%{zone2}"
  }

  boot_disk {
    auto_delete = false
    source      = google_compute_region_disk.regional_disk.self_link
  }

  network_interface {
    network = "default"
  }

  allow_stopping_for_update = true
}

resource "google_compute_ha_controller" "foobar" {
  name                = "%{hac_name}"
  region              = "%{region}"
  instance_name       = google_compute_instance.vm.name
  failover_initiation = "MANUAL_ONLY"

  zone_configuration {
    zone = "%{zone1}"
  }
  zone_configuration {
    zone = "%{zone2}"
  }
}
`, context)
}

func testAccHaController_noHac(context map[string]interface{}) string {
	return acctest.Nprintf(`
data "google_compute_image" "debian_12" {
  family   = "debian-12"
  project  = "debian-cloud"
}

resource "google_compute_region_disk" "regional_disk" {
  name                      = "%{hac_name}-rd"
  physical_block_size_bytes = 4096
  type                      = "pd-balanced"
  region                    = "%{region}"
  replica_zones             = ["%{zone1}", "%{zone2}"]
  size                      = 15
  image                     = data.google_compute_image.debian_12.self_link
}

resource "google_compute_instance" "vm" {
  name         = "%{hac_name}-inst"
  machine_type = "e2-micro"
  zones {
    zone = "%{zone1}"
  }
  zones {
    zone = "%{zone2}"
  }

  boot_disk {
    auto_delete = false
    source      = google_compute_region_disk.regional_disk.self_link
  }

  network_interface {
    network = "default"
  }

  allow_stopping_for_update = true
}
`, context)
}
