// Copyright IBM Corp. 2014, 2026
// Copyright 2026 Google LLC
// SPDX-License-Identifier: MPL-2.0
// ----------------------------------------------------------------------------
//
//	***     AUTO GENERATED CODE    ***    Type: Handwritten     ***
//
// ----------------------------------------------------------------------------
//
//	This code is generated by Magic Modules using the following:
//
//	Source file: https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/services/compute/resource_compute_instance_internal_test.go
//
//	DO NOT EDIT this file directly. Any changes made to this file will be
//	overwritten during the next generation cycle.
//
// ----------------------------------------------------------------------------
package compute

import (
	"testing"

	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/tpgresource"
)

func TestComputeInstance_networkIPCustomizedDiff(t *testing.T) {
	t.Parallel()

	d := &tpgresource.ResourceDiffMock{
		Before: map[string]interface{}{
			"network_interface.#": 0,
		},
		After: map[string]interface{}{
			"network_interface.#": 1,
		},
	}

	err := forceNewIfNetworkIPNotUpdatableFunc(d)
	if err != nil {
		t.Error(err)
	}

	if d.IsForceNew {
		t.Errorf("Expected not force new if network_interface array size changes")
	}

	type NetworkInterface struct {
		Network           string
		Subnetwork        string
		SubnetworkProject string
		NetworkIP         string
	}
	NIBefore := NetworkInterface{
		Network:           "a",
		Subnetwork:        "a",
		SubnetworkProject: "a",
		NetworkIP:         "a",
	}

	cases := map[string]struct {
		ExpectedForceNew bool
		Before           NetworkInterface
		After            NetworkInterface
	}{
		"NetworkIP only change": {
			ExpectedForceNew: true,
			Before:           NIBefore,
			After: NetworkInterface{
				Network:           "a",
				Subnetwork:        "a",
				SubnetworkProject: "a",
				NetworkIP:         "b",
			},
		},
		"NetworkIP and Network change": {
			ExpectedForceNew: false,
			Before:           NIBefore,
			After: NetworkInterface{
				Network:           "b",
				Subnetwork:        "a",
				SubnetworkProject: "a",
				NetworkIP:         "b",
			},
		},
		"NetworkIP and Subnetwork change": {
			ExpectedForceNew: false,
			Before:           NIBefore,
			After: NetworkInterface{
				Network:           "a",
				Subnetwork:        "b",
				SubnetworkProject: "a",
				NetworkIP:         "b",
			},
		},
		"NetworkIP and SubnetworkProject change": {
			ExpectedForceNew: false,
			Before:           NIBefore,
			After: NetworkInterface{
				Network:           "a",
				Subnetwork:        "a",
				SubnetworkProject: "b",
				NetworkIP:         "b",
			},
		},
		"All change": {
			ExpectedForceNew: false,
			Before:           NIBefore,
			After: NetworkInterface{
				Network:           "b",
				Subnetwork:        "b",
				SubnetworkProject: "b",
				NetworkIP:         "b",
			},
		},
		"No change": {
			ExpectedForceNew: false,
			Before:           NIBefore,
			After: NetworkInterface{
				Network:           "a",
				Subnetwork:        "a",
				SubnetworkProject: "a",
				NetworkIP:         "a",
			},
		},
	}

	for tn, tc := range cases {
		d := &tpgresource.ResourceDiffMock{
			Before: map[string]interface{}{
				"network_interface.#":                    1,
				"network_interface.0.network":            tc.Before.Network,
				"network_interface.0.subnetwork":         tc.Before.Subnetwork,
				"network_interface.0.subnetwork_project": tc.Before.SubnetworkProject,
				"network_interface.0.network_ip":         tc.Before.NetworkIP,
			},
			After: map[string]interface{}{
				"network_interface.#":                    1,
				"network_interface.0.network":            tc.After.Network,
				"network_interface.0.subnetwork":         tc.After.Subnetwork,
				"network_interface.0.subnetwork_project": tc.After.SubnetworkProject,
				"network_interface.0.network_ip":         tc.After.NetworkIP,
			},
		}
		err := forceNewIfNetworkIPNotUpdatableFunc(d)
		if err != nil {
			t.Error(err)
		}
		if tc.ExpectedForceNew != d.IsForceNew {
			t.Errorf("%v: expected d.IsForceNew to be %v, but was %v", tn, tc.ExpectedForceNew, d.IsForceNew)
		}
	}
}

func TestComputeInstance_validateZones(t *testing.T) {
	t.Parallel()

	cases := map[string]struct {
		Zones       []interface{}
		ExpectError bool
	}{
		"success - 2 distinct zones in same region": {
			Zones: []interface{}{
				map[string]interface{}{"zone": "us-central1-a"},
				map[string]interface{}{"zone": "us-central1-b"},
			},
			ExpectError: false,
		},
		"success - 3 distinct zones in same region": {
			Zones: []interface{}{
				map[string]interface{}{"zone": "us-central1-a"},
				map[string]interface{}{"zone": "us-central1-b"},
				map[string]interface{}{"zone": "us-central1-c"},
			},
			ExpectError: false,
		},
		"failure - fewer than 2 zones": {
			Zones: []interface{}{
				map[string]interface{}{"zone": "us-central1-a"},
			},
			ExpectError: true,
		},
		"failure - duplicate zones": {
			Zones: []interface{}{
				map[string]interface{}{"zone": "us-central1-a"},
				map[string]interface{}{"zone": "us-central1-b"},
				map[string]interface{}{"zone": "us-central1-a"},
			},
			ExpectError: true,
		},
		"failure - mismatching regions": {
			Zones: []interface{}{
				map[string]interface{}{"zone": "us-central1-a"},
				map[string]interface{}{"zone": "europe-west1-b"},
			},
			ExpectError: true,
		},
		"failure - invalid zone format": {
			Zones: []interface{}{
				map[string]interface{}{"zone": "uscentral1a"},
				map[string]interface{}{"zone": "us-central1-b"},
			},
			ExpectError: true,
		},
	}

	for tn, tc := range cases {
		t.Run(tn, func(t *testing.T) {
			d := &tpgresource.ResourceDiffMock{
				After: map[string]interface{}{
					"zones": tc.Zones,
				},
			}
			err := validateZones(d)
			if tc.ExpectError && err == nil {
				t.Fatalf("expected error, but got nil")
			}
			if !tc.ExpectError && err != nil {
				t.Fatalf("unexpected error: %s", err)
			}
		})
	}
}

func TestComputeInstance_customizeZonesDiffFunc(t *testing.T) {
	t.Parallel()

	cases := map[string]struct {
		RemoteZone     string
		ConfigZone     string
		Zones          []interface{}
		ExpectSetNew   bool
		ExpectVal      interface{}
		ExpectComputed bool
	}{
		"fewer than 2 zones - no change": {
			RemoteZone:     "us-central1-a",
			ConfigZone:     "us-central1-b",
			Zones:          []interface{}{map[string]interface{}{"zone": "us-central1-a"}},
			ExpectSetNew:   false,
			ExpectVal:      nil,
			ExpectComputed: false,
		},
		"2 zones, remoteZone not empty, configZone empty, remoteZone is in zones": {
			RemoteZone: "us-central1-a",
			ConfigZone: "",
			Zones: []interface{}{
				map[string]interface{}{"zone": "us-central1-a"},
				map[string]interface{}{"zone": "us-central1-b"},
			},
			ExpectSetNew:   true,
			ExpectVal:      "us-central1-a",
			ExpectComputed: false,
		},
		"2 zones, remoteZone not empty, configZone empty, remoteZone is not in zones": {
			RemoteZone: "us-central1-c",
			ConfigZone: "",
			Zones: []interface{}{
				map[string]interface{}{"zone": "us-central1-a"},
				map[string]interface{}{"zone": "us-central1-b"},
			},
			ExpectSetNew:   true,
			ExpectVal:      "us-central1-c",
			ExpectComputed: true,
		},
		"2 zones, configZone is in zones": {
			RemoteZone: "us-central1-a",
			ConfigZone: "us-central1-b",
			Zones: []interface{}{
				map[string]interface{}{"zone": "us-central1-a"},
				map[string]interface{}{"zone": "us-central1-b"},
			},
			ExpectSetNew:   false,
			ExpectVal:      nil,
			ExpectComputed: false,
		},
		"2 zones, configZone is not in zones": {
			RemoteZone: "us-central1-a",
			ConfigZone: "us-central1-c",
			Zones: []interface{}{
				map[string]interface{}{"zone": "us-central1-a"},
				map[string]interface{}{"zone": "us-central1-b"},
			},
			ExpectSetNew:   false,
			ExpectVal:      nil,
			ExpectComputed: true,
		},
	}

	for tn, tc := range cases {
		t.Run(tn, func(t *testing.T) {
			d := &tpgresource.ResourceDiffMock{
				Before: map[string]interface{}{
					"zone": tc.RemoteZone,
				},
				After: map[string]interface{}{
					"zone":  tc.ConfigZone,
					"zones": tc.Zones,
				},
			}
			setNew, setNewVal, setNewComputed := customizeZonesDiffFunc(d)
			if setNew != tc.ExpectSetNew {
				t.Errorf("setNew was %v, expected %v", setNew, tc.ExpectSetNew)
			}
			if setNewVal != tc.ExpectVal {
				t.Errorf("setNewVal was %v, expected %v", setNewVal, tc.ExpectVal)
			}
			if setNewComputed != tc.ExpectComputed {
				t.Errorf("setNewComputed was %v, expected %v", setNewComputed, tc.ExpectComputed)
			}
		})
	}
}
