// Copyright IBM Corp. 2014, 2026
// Copyright 2026 Google LLC
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package compute_test

import (
	"fmt"
	"log"
	"regexp"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"

	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/acctest"
	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/envvar"
	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/services/compute"
	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/tpgresource"
	transport_tpg "github.com/hashicorp/terraform-provider-google-nightly/google-nightly/transport"

	"google.golang.org/api/googleapi"
)

var (
	_ = fmt.Sprintf
	_ = log.Print
	_ = regexp.MatchString
	_ = strconv.Atoi
	_ = strings.Trim
	_ = time.Now
	_ = resource.TestMain
	_ = terraform.NewState
	_ = envvar.TestEnvVar
	_ = tpgresource.SetLabels
	_ = transport_tpg.Config{}
	_ = googleapi.Error{}
	_ = compute.Product
)

func TestAccComputeHaController_computeHaControllerBasicExample(t *testing.T) {
	t.Parallel()

	randomSuffix := acctest.RandString(t, 10)

	context := map[string]interface{}{
		"hac_name":      "tf-test-hac-bs" + randomSuffix,
		"random_suffix": randomSuffix,
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderBetaFactories(t),
		CheckDestroy:             testAccCheckComputeHaControllerDestroyProducer(t),
		Steps: []resource.TestStep{
			{
				Config: testAccComputeHaController_computeHaControllerBasicExample(context),
			},
			{
				ResourceName:            "google_compute_ha_controller.default",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"region"},
			},
			{
				ResourceName:       "google_compute_ha_controller.default",
				RefreshState:       true,
				ExpectNonEmptyPlan: true,
				ImportStateKind:    resource.ImportBlockWithResourceIdentity,
			},
		},
	})
}

func testAccComputeHaController_computeHaControllerBasicExample(context map[string]interface{}) string {
	return acctest.Nprintf(`
locals {
  region          = "us-central1"
  zone1           = "us-central1-a"
  zone2           = "us-central1-b"
}

data "google_compute_image" "debian_12" {
  provider = google-private
  family   = "debian-12"
  project  = "debian-cloud"
}

resource "google_compute_region_disk" "regional_disk" {
  provider                  = google-private
  name                      = "%{hac_name}-rd"
  physical_block_size_bytes = 4096
  type                      = "pd-balanced"
  region                    = local.region
  replica_zones             = [local.zone1, local.zone2]
  size                      = 10
  image                     = data.google_compute_image.debian_12.self_link
}

resource "google_compute_instance" "vm" {
  provider     = google-private
  name         = "%{hac_name}-inst"
  machine_type = "e2-micro"
  zone         = local.zone1

  boot_disk {
    auto_delete = false
    source      = google_compute_region_disk.regional_disk.self_link
  }

  network_interface {
    network = "default"
  }

  allow_stopping_for_update = true
}

resource "google_compute_ha_controller" "default" {
  provider            = google-private
  name                = "%{hac_name}"
  region              = local.region
  instance_name       = google_compute_instance.vm.name
  failover_initiation = "MANUAL_ONLY"

  zone_configuration {
    zone = local.zone1
  }
  zone_configuration {
    zone = local.zone2
  }
}
`, context)
}

func TestAccComputeHaController_computeHaControllerReservationsExample(t *testing.T) {
	t.Parallel()

	randomSuffix := acctest.RandString(t, 10)

	context := map[string]interface{}{
		"hac_name":      "tf-test-hac-rv" + randomSuffix,
		"random_suffix": randomSuffix,
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderBetaFactories(t),
		CheckDestroy:             testAccCheckComputeHaControllerDestroyProducer(t),
		Steps: []resource.TestStep{
			{
				Config: testAccComputeHaController_computeHaControllerReservationsExample(context),
			},
			{
				ResourceName:            "google_compute_ha_controller.default",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"region"},
			},
			{
				ResourceName:       "google_compute_ha_controller.default",
				RefreshState:       true,
				ExpectNonEmptyPlan: true,
				ImportStateKind:    resource.ImportBlockWithResourceIdentity,
			},
		},
	})
}

func testAccComputeHaController_computeHaControllerReservationsExample(context map[string]interface{}) string {
	return acctest.Nprintf(`
locals {
  region          = "us-central1"
  zone1           = "us-central1-a"
  zone2           = "us-central1-b"
}

data "google_compute_image" "debian_12" {
  provider = google-private
  family   = "debian-12"
  project  = "debian-cloud"
}

resource "google_compute_region_disk" "regional_disk" {
  provider                  = google-private
  name                      = "%{hac_name}-rd"
  physical_block_size_bytes = 4096
  type                      = "pd-balanced"
  region                    = local.region
  replica_zones             = [local.zone1, local.zone2]
  size                      = 10
  image                     = data.google_compute_image.debian_12.self_link
}

resource "google_compute_reservation" "reservation_zone1" {
  provider = google-private
  name     = "%{hac_name}-rv" # same name as in zone 2
  zone     = local.zone1

  specific_reservation {
    count = 1
    instance_properties {
      machine_type = "e2-micro"
    }
  }

  reservation_sharing_policy {
    service_share_type = "DISALLOW_ALL"
  }

  specific_reservation_required = true
}

resource "google_compute_reservation" "reservation_zone2" {
  provider = google-private
  name     = "%{hac_name}-rv" # same name as in zone 1
  zone     = local.zone2

  specific_reservation {
    count = 1
    instance_properties {
      machine_type = "e2-micro"
    }
  }

  reservation_sharing_policy {
    service_share_type = "DISALLOW_ALL"
  }

  specific_reservation_required = true
}

resource "google_compute_instance" "vm" {
  provider     = google-private
  name         = "%{hac_name}-inst"
  machine_type = "e2-micro"
  zone         = local.zone1

  boot_disk {
    auto_delete = false
    source      = google_compute_region_disk.regional_disk.self_link
  }

  network_interface {
    subnetwork = "default"
    stack_type = "IPV4_ONLY"
  }

  reservation_affinity {
    type = "SPECIFIC_RESERVATION"
    specific_reservation {
      key    = "compute.googleapis.com/reservation-name"
      values = [google_compute_reservation.reservation_zone1.name]
    }
  }

  allow_stopping_for_update = true
}

resource "google_compute_ha_controller" "default" {
  provider            = google-private
  name                = "%{hac_name}"
  region              = local.region
  instance_name       = google_compute_instance.vm.name
  failover_initiation = "MANUAL_ONLY"

  networking_auto_configuration {
    internal {
      stack_type = "IPV4_ONLY"
    }
  }

  zone_configuration {
    zone = local.zone1
    reservation_affinity {
      type = "SPECIFIC_RESERVATION"
      specific_reservation {
        key    = "compute.googleapis.com/reservation-name"
        values = [google_compute_reservation.reservation_zone1.name]
      }
    }
  }
  zone_configuration {
    zone = local.zone2
    reservation_affinity {
      type = "SPECIFIC_RESERVATION"
      specific_reservation {
        key    = "compute.googleapis.com/reservation-name"
        values = [google_compute_reservation.reservation_zone2.name]
      }
    }
  }
}
`, context)
}

func TestAccComputeHaController_computeHaControllerSoleTenancyExample(t *testing.T) {
	t.Parallel()

	randomSuffix := acctest.RandString(t, 10)

	context := map[string]interface{}{
		"hac_name":      "tf-test-hac-st" + randomSuffix,
		"random_suffix": randomSuffix,
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderBetaFactories(t),
		CheckDestroy:             testAccCheckComputeHaControllerDestroyProducer(t),
		Steps: []resource.TestStep{
			{
				Config: testAccComputeHaController_computeHaControllerSoleTenancyExample(context),
			},
			{
				ResourceName:            "google_compute_ha_controller.default",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"region"},
			},
			{
				ResourceName:       "google_compute_ha_controller.default",
				RefreshState:       true,
				ExpectNonEmptyPlan: true,
				ImportStateKind:    resource.ImportBlockWithResourceIdentity,
			},
		},
	})
}

func testAccComputeHaController_computeHaControllerSoleTenancyExample(context map[string]interface{}) string {
	return acctest.Nprintf(`
locals {
  region          = "us-central1"
  zone1           = "us-central1-a"
  zone2           = "us-central1-b"
}

data "google_compute_image" "debian_12" {
  provider = google-private
  family   = "debian-12"
  project  = "debian-cloud"
}

resource "google_compute_region_disk" "regional_disk" {
  provider                  = google-private
  name                      = "%{hac_name}-rd"
  physical_block_size_bytes = 4096
  type                      = "pd-balanced"
  region                    = local.region
  replica_zones             = [local.zone1, local.zone2]
  size                      = 10
  image                     = data.google_compute_image.debian_12.self_link
}

resource "google_compute_node_template" "node_template1" {
  provider  = google-private
  name      = "%{hac_name}-ntmpl"
  region    = local.region
  node_type = "n1-node-96-624"
  node_affinity_labels = {
    workload = "synthetic"
    distinct = "1"
  }
}

resource "google_compute_node_template" "node_template2" {
  provider  = google-private
  name      = "%{hac_name}-ntmpl2"
  region    = local.region
  node_type = "n1-node-96-624"
  node_affinity_labels = {
    workload = "synthetic"
    distinct = "2"
  }
}

resource "google_compute_node_group" "sole_tenant_group1" {
  provider      = google-private
  name          = "%{hac_name}-stgrp1"
  zone          = local.zone1
  node_template = google_compute_node_template.node_template1.id
  initial_size  = 1
}

resource "google_compute_node_group" "sole_tenant_group2" {
  provider      = google-private
  name          = "%{hac_name}-stgrp2"
  zone          = local.zone2
  node_template = google_compute_node_template.node_template2.id
  initial_size  = 1
}

resource "google_compute_instance" "vm" {
  provider     = google-private
  name         = "%{hac_name}-inst"
  machine_type = "n1-standard-1"
  zone         = local.zone1

  depends_on = [
    google_compute_node_group.sole_tenant_group1,
    google_compute_node_group.sole_tenant_group2,
  ]

  boot_disk {
    auto_delete = false
    source      = google_compute_region_disk.regional_disk.self_link
  }

  network_interface {
    subnetwork = "default"
    stack_type = "IPV4_ONLY"
  }

  scheduling {
    node_affinities {
      key      = "workload"
      operator = "IN"
      values   = ["synthetic"]
    }
  }

  allow_stopping_for_update = true
}

resource "google_compute_ha_controller" "default" {
  provider            = google-private
  name                = "%{hac_name}"
  region              = local.region
  instance_name       = google_compute_instance.vm.name
  failover_initiation = "MANUAL_ONLY"

  zone_configuration {
    zone = local.zone1
    node_affinities {
      key      = "workload"
      operator = "IN"
      values   = ["synthetic"]
    }
  }
  zone_configuration {
    zone = local.zone2
    node_affinities {
      key      = "workload"
      operator = "IN"
      values   = ["synthetic"]
    }
  }
}
`, context)
}

func testAccCheckComputeHaControllerDestroyProducer(t *testing.T) func(s *terraform.State) error {
	return func(s *terraform.State) error {
		for name, rs := range s.RootModule().Resources {
			if rs.Type != "google_compute_ha_controller" {
				continue
			}
			if strings.HasPrefix(name, "data.") {
				continue
			}

			config := acctest.GoogleProviderConfig(t)
			url, err := tpgresource.ReplaceVarsForTest(config, rs, transport_tpg.BaseUrl(compute.Product, config)+"projects/{{project}}/regions/{{region}}/haControllers/{{name}}")
			if err != nil {
				return err
			}

			billingProject := ""

			if config.BillingProject != "" {
				billingProject = config.BillingProject
			}

			_, err = transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
				Config:    config,
				Method:    "GET",
				Project:   billingProject,
				RawURL:    url,
				UserAgent: config.UserAgent,
			})
			if err == nil {
				return fmt.Errorf("ComputeHaController still exists at %s", url)
			}
		}

		return nil
	}
}
