// Copyright IBM Corp. 2014, 2026
// Copyright 2026 Google LLC
// SPDX-License-Identifier: MPL-2.0
// ----------------------------------------------------------------------------
//
//	***     AUTO GENERATED CODE    ***    Type: Handwritten     ***
//
// ----------------------------------------------------------------------------
//
//	This code is generated by Magic Modules using the following:
//
//	Source file: https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/services/compute/resource_compute_router_peer_test.go.tmpl
//
//	DO NOT EDIT this file directly. Any changes made to this file will be
//	overwritten during the next generation cycle.
//
// ----------------------------------------------------------------------------
package compute_test

import (
	"fmt"
	"strings"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"

	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/acctest"
	_ "github.com/hashicorp/terraform-provider-google-nightly/google-nightly/services/compute"
	_ "github.com/hashicorp/terraform-provider-google-nightly/google-nightly/services/networkconnectivity"
	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/tpgresource"
	transport_tpg "github.com/hashicorp/terraform-provider-google-nightly/google-nightly/transport"
)

func TestAccComputeRouterBgpPeer_routerPeerRouterAppliance(t *testing.T) {
	t.Parallel()

	context := map[string]interface{}{
		"random_suffix": acctest.RandString(t, 10),
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactories(t),
		CheckDestroy:             testAccCheckComputeRouterBgpPeerDestroyProducer(t),
		Steps: []resource.TestStep{
			{
				Config: testAccComputeRouterBgpPeer_routerPeerRouterAppliance(context),
			},
			{
				ResourceName:            "google_compute_router_peer.peer",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"router_appliance_instance", "router", "region", "zero_custom_learned_route_priority"},
			},
		},
	})
}

func testAccComputeRouterBgpPeer_routerPeerRouterAppliance(context map[string]interface{}) string {
	return acctest.Nprintf(`
resource "google_compute_network" "network" {
  name                    = "tf-test-my-router%{random_suffix}-net"
  auto_create_subnetworks = false
}

resource "google_compute_subnetwork" "subnetwork" {
  name          = "tf-test-my-router%{random_suffix}-sub"
  network       = google_compute_network.network.self_link
  ip_cidr_range = "10.0.0.0/16"
  region        = "us-central1"
}

resource "google_compute_address" "addr_intf" {
  name         = "tf-test-my-router%{random_suffix}-addr-intf"
  region       = google_compute_subnetwork.subnetwork.region
  subnetwork   = google_compute_subnetwork.subnetwork.id
  address_type = "INTERNAL"
}

resource "google_compute_address" "addr_intf_redundant" {
  name         = "tf-test-my-router%{random_suffix}-addr-intf-red"
  region       = google_compute_subnetwork.subnetwork.region
  subnetwork   = google_compute_subnetwork.subnetwork.id
  address_type = "INTERNAL"
}

resource "google_compute_address" "addr_peer" {
  name         = "tf-test-my-router%{random_suffix}-addr-peer"
  region       = google_compute_subnetwork.subnetwork.region
  subnetwork   = google_compute_subnetwork.subnetwork.id
  address_type = "INTERNAL"
}

resource "google_compute_instance" "instance" {
  name           = "tf-test-router-appliance%{random_suffix}"
  zone           = "us-central1-a"
  machine_type   = "e2-medium"
  can_ip_forward = true

  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-13"
    }
  }

  network_interface {
    network_ip = google_compute_address.addr_peer.address
    subnetwork = google_compute_subnetwork.subnetwork.self_link
  }
}

resource "google_network_connectivity_hub" "hub" {
  name = "tf-test-my-router%{random_suffix}-hub"
}

resource "google_network_connectivity_spoke" "spoke" {
  name     = "tf-test-my-router%{random_suffix}-spoke"
  location = google_compute_subnetwork.subnetwork.region
  hub      = google_network_connectivity_hub.hub.id

  linked_router_appliance_instances {
    instances {
      virtual_machine = google_compute_instance.instance.self_link
      ip_address      = google_compute_address.addr_peer.address
    }
    site_to_site_data_transfer = false
  }
}

resource "google_compute_router" "router" {
  name    = "tf-test-my-router%{random_suffix}-router"
  region  = google_compute_subnetwork.subnetwork.region
  network = google_compute_network.network.self_link
  bgp {
    asn = 64514
  }
}

resource "google_compute_router_interface" "interface_redundant" {
  name               = "tf-test-my-router%{random_suffix}-intf-red"
  region             = google_compute_router.router.region
  router             = google_compute_router.router.name
  subnetwork         = google_compute_subnetwork.subnetwork.self_link
  private_ip_address = google_compute_address.addr_intf_redundant.address
}

resource "google_compute_router_interface" "interface" {
  name                = "tf-test-my-router%{random_suffix}-intf"
  region              = google_compute_router.router.region
  router              = google_compute_router.router.name
  subnetwork          = google_compute_subnetwork.subnetwork.self_link
  private_ip_address  = google_compute_address.addr_intf.address
  redundant_interface = google_compute_router_interface.interface_redundant.name
}

resource "google_compute_router_peer" "peer" {
  name                      = "tf-test-my-router-peer%{random_suffix}"
  router                    = google_compute_router.router.name
  region                    = google_compute_router.router.region
  interface                 = google_compute_router_interface.interface.name
  router_appliance_instance = google_compute_instance.instance.self_link
  peer_asn                  = 65513
  peer_ip_address           = google_compute_address.addr_peer.address
  depends_on = [
    google_network_connectivity_spoke.spoke
  ]
}
`, context)
}

func testAccCheckComputeRouterBgpPeerDestroyProducer(t *testing.T) func(s *terraform.State) error {
	return func(s *terraform.State) error {
		for name, rs := range s.RootModule().Resources {
			if rs.Type != "google_compute_router_peer" {
				continue
			}
			if strings.HasPrefix(name, "data.") {
				continue
			}

			config := acctest.GoogleProviderConfig(t)

			url, err := tpgresource.ReplaceVarsForTest(config, rs, "{{ComputeBasePath}}projects/{{project}}/regions/{{region}}/routers/{{router}}")
			if err != nil {
				return err
			}

			billingProject := ""

			if config.BillingProject != "" {
				billingProject = config.BillingProject
			}

			_, err = transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
				Config:    config,
				Method:    "GET",
				Project:   billingProject,
				RawURL:    url,
				UserAgent: config.UserAgent,
			})
			if err == nil {
				return fmt.Errorf("ComputeRouterBgpPeer still exists at %s", url)
			}
		}

		return nil
	}
}
func TestAccComputeRouterBgpPeer_routerPeerLinkedCustomHardware(t *testing.T) {
	t.Parallel()
	context := map[string]interface{}{
		"random_suffix": acctest.RandString(t, 10),
	}
	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactories(t),
		CheckDestroy:             testAccCheckComputeRouterBgpPeerDestroyProducer(t),
		Steps: []resource.TestStep{
			{
				Config: testAccComputeRouterBgpPeer_routerPeerLinkedCustomHardware(context),
			},
			{
				ResourceName:            "google_compute_router_peer.peer",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"router", "region", "zero_custom_learned_route_priority"},
			},
		},
	})
}
func testAccComputeRouterBgpPeer_routerPeerLinkedCustomHardware(context map[string]interface{}) string {
	return acctest.Nprintf(`
resource "google_compute_network" "network" {
  name                    = "tf-test-my-router%{random_suffix}-net"
  auto_create_subnetworks = false
}
resource "google_compute_subnetwork" "subnetwork" {
  name          = "tf-test-my-router%{random_suffix}-sub"
  network       = google_compute_network.network.self_link
  ip_cidr_range = "10.0.0.0/16"
  region        = "us-south1"
}
resource "google_compute_subnetwork" "ch_subnetwork" {
  name          = "tf-test-my-router%{random_suffix}-chsub"
  network       = google_compute_network.network.name
  ip_cidr_range = "192.168.176.0/20"
  region        = "us-south1"
  purpose       = "CUSTOM_HARDWARE_LINK"
}
resource "google_compute_address" "bgp_a" {
  name         = "tf-test-my-router%{random_suffix}-bgp-a"
  region       = "us-south1"
  address_type = "INTERNAL"
  purpose      = "SYSTEM_MANAGED"
  subnetwork   = google_compute_subnetwork.subnetwork.id
}
resource "google_compute_address" "bgp_peer_a" {
  name         = "tf-test-my-router%{random_suffix}-peer-a"
  region       = "us-south1"
  address_type = "INTERNAL"
  purpose      = "SYSTEM_MANAGED"
  subnetwork   = google_compute_subnetwork.subnetwork.id
}
resource "google_compute_address" "ch_range" {
  name         = "tf-test-my-router%{random_suffix}-range"
  region       = "us-south1"
  address_type = "INTERNAL"
  purpose      = "SYSTEM_MANAGED"
  subnetwork   = google_compute_subnetwork.ch_subnetwork.id
  address      = "192.168.177.0"
}
resource "google_network_connectivity_custom_hardware_instance" "instance" {
  name     = "tf-test-ch-inst%{random_suffix}"
  location = "us-south1"
}
resource "google_network_connectivity_custom_hardware_link_connect_pair" "pair" {
  name                     = "tf-test-ch-lcp%{random_suffix}"
  location                 = "us-south1-d"
  custom_hardware_instance = google_network_connectivity_custom_hardware_instance.instance.id
  link_type                = "LINK_TYPE_REGULAR"
  link_speed               = "LINK_SPEED100_G"
}
resource "google_network_connectivity_custom_hardware_link_attachment" "attachment" {
  name                              = "tf-test-ch-la%{random_suffix}"
  location                          = "us-south1-d"
  custom_hardware_link_connect_pair = google_network_connectivity_custom_hardware_link_connect_pair.pair.id
  subnetwork                        = google_compute_subnetwork.subnetwork.id
  link_type                         = "LINK_TYPE_REGULAR"
  bgp_ip                            = google_compute_address.bgp_a.id
  asn                               = "64512"
  peer_bgp_ip                       = google_compute_address.bgp_peer_a.id
  peer_asn                          = "64513"
  link_address_range                = google_compute_address.ch_range.id
}
resource "google_compute_router" "router" {
  name    = "tf-test-my-router%{random_suffix}"
  region  = google_compute_subnetwork.subnetwork.region
  network = google_compute_network.network.self_link
  bgp {
    asn = 64514
  }
}
resource "google_compute_router_interface" "interface" {
  name                = "tf-test-my-router%{random_suffix}-intf"
  region              = google_compute_router.router.region
  router              = google_compute_router.router.name
  subnetwork          = google_compute_subnetwork.subnetwork.self_link
  lifecycle {
    # The backend assigns private_ip_address when the peer uses linked_custom_hardware.
    ignore_changes = [private_ip_address]
  }
}
resource "google_compute_router_peer" "peer" {
  name                   = "tf-test-my-router-peer%{random_suffix}"
  router                 = google_compute_router.router.name
  region                 = google_compute_router.router.region
  interface              = google_compute_router_interface.interface.name
  linked_custom_hardware = google_network_connectivity_custom_hardware_link_attachment.attachment.id
  peer_asn               = 64513
  peer_ip_address        = google_compute_address.bgp_peer_a.address
}
`, context)
}
