// Copyright IBM Corp. 2014, 2026
// Copyright 2026 Google LLC
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package networkconnectivity_test

import (
	"fmt"
	"log"
	"regexp"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"

	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/acctest"
	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/envvar"
	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/services/networkconnectivity"
	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/tpgresource"
	transport_tpg "github.com/hashicorp/terraform-provider-google-nightly/google-nightly/transport"

	"google.golang.org/api/googleapi"
)

var (
	_ = fmt.Sprintf
	_ = log.Print
	_ = regexp.MatchString
	_ = strconv.Atoi
	_ = strings.Trim
	_ = time.Now
	_ = resource.TestMain
	_ = terraform.NewState
	_ = envvar.TestEnvVar
	_ = tpgresource.SetLabels
	_ = transport_tpg.Config{}
	_ = googleapi.Error{}
	_ = networkconnectivity.Product
)

func TestAccNetworkConnectivityCustomHardwareLinkConnectPair_networkConnectivityCustomHardwareLinkConnectPairBasicExample(t *testing.T) {
	t.Parallel()

	randomSuffix := acctest.RandString(t, 10)

	context := map[string]interface{}{
		"resource_name": "tf-test-ch-test-lcp" + randomSuffix,
		"random_suffix": randomSuffix,
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderBetaFactories(t),
		CheckDestroy:             testAccCheckNetworkConnectivityCustomHardwareLinkConnectPairDestroyProducer(t),
		Steps: []resource.TestStep{
			{
				Config: testAccNetworkConnectivityCustomHardwareLinkConnectPair_networkConnectivityCustomHardwareLinkConnectPairBasicExample(context),
			},
			{
				ResourceName:            "google_network_connectivity_custom_hardware_link_connect_pair.pair",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"labels", "location", "terraform_labels"},
			},
			{
				ResourceName:       "google_network_connectivity_custom_hardware_link_connect_pair.pair",
				RefreshState:       true,
				ExpectNonEmptyPlan: true,
				ImportStateKind:    resource.ImportBlockWithResourceIdentity,
			},
		},
	})
}

func testAccNetworkConnectivityCustomHardwareLinkConnectPair_networkConnectivityCustomHardwareLinkConnectPairBasicExample(context map[string]interface{}) string {
	return acctest.Nprintf(`
provider "google-nightly" {}

resource "google_network_connectivity_custom_hardware_instance" "instance" {
  provider = google-nightly
  name = "%{resource_name}-inst"
  location = "us-south1"
}

resource "google_network_connectivity_custom_hardware_link_connect_pair" "pair" {
  provider = google-nightly
  name = "%{resource_name}"
  location = "us-south1-d"
  custom_hardware_instance = google_network_connectivity_custom_hardware_instance.instance.id
  link_type = "LINK_TYPE_REGULAR"
  link_speed = "LINK_SPEED100_G"
  full_diversity_disabled = false
}

resource "google_network_connectivity_custom_hardware_instance" "instance2" {
  provider = google-nightly
  name = "%{resource_name}-inst2"
  location = "us-south1"
}

resource "google_network_connectivity_custom_hardware_link_connect_pair" "pair2" {
  provider = google-nightly
  name = "%{resource_name}2"
  location = "us-south1-d"
  custom_hardware_instance = google_network_connectivity_custom_hardware_instance.instance2.id
  link_type = "LINK_TYPE_ULL"
  link_speed = "LINK_SPEED10_G"
  full_diversity_disabled = true
}
`, context)
}

func testAccCheckNetworkConnectivityCustomHardwareLinkConnectPairDestroyProducer(t *testing.T) func(s *terraform.State) error {
	return func(s *terraform.State) error {
		for name, rs := range s.RootModule().Resources {
			if rs.Type != "google_network_connectivity_custom_hardware_link_connect_pair" {
				continue
			}
			if strings.HasPrefix(name, "data.") {
				continue
			}

			config := acctest.GoogleProviderConfig(t)
			url, err := tpgresource.ReplaceVarsForTest(config, rs, transport_tpg.BaseUrl(networkconnectivity.Product, config)+"projects/{{project}}/locations/{{location}}/customHardwareLinkConnectPairs/{{name}}")
			if err != nil {
				return err
			}

			billingProject := ""

			if config.BillingProject != "" {
				billingProject = config.BillingProject
			}

			_, err = transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
				Config:    config,
				Method:    "GET",
				Project:   billingProject,
				RawURL:    url,
				UserAgent: config.UserAgent,
			})
			if err == nil {
				return fmt.Errorf("NetworkConnectivityCustomHardwareLinkConnectPair still exists at %s", url)
			}
		}

		return nil
	}
}
