// Copyright IBM Corp. 2014, 2026
// Copyright 2026 Google LLC
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package networkconnectivity_test

import (
	"fmt"
	"log"
	"regexp"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/plancheck"
	"github.com/hashicorp/terraform-plugin-testing/terraform"

	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/acctest"
	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/envvar"
	_ "github.com/hashicorp/terraform-provider-google-nightly/google-nightly/services/compute"
	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/services/networkconnectivity"
	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/tpgresource"
	transport_tpg "github.com/hashicorp/terraform-provider-google-nightly/google-nightly/transport"

	"google.golang.org/api/googleapi"
)

var (
	_ = fmt.Sprintf
	_ = log.Print
	_ = regexp.MatchString
	_ = strconv.Atoi
	_ = strings.Trim
	_ = time.Now
	_ = resource.TestMain
	_ = terraform.NewState
	_ = envvar.TestEnvVar
	_ = tpgresource.SetLabels
	_ = transport_tpg.Config{}
	_ = googleapi.Error{}
	_ = networkconnectivity.Product
)

func TestAccNetworkConnectivityCustomHardwareLinkAttachment_networkConnectivityCustomHardwareLinkAttachmentBasicExample(t *testing.T) {
	t.Parallel()

	randomSuffix := acctest.RandString(t, 10)

	context := map[string]interface{}{
		"network_name":  "tf-test-chn-test-gray-network" + randomSuffix,
		"range_address": "192.168.177.0",
		"range_name":    "tf-test-chn-test-gray-range" + randomSuffix,
		"resource_name": "tf-test-chn-test-gray" + randomSuffix,
		"random_suffix": randomSuffix,
	}

	context_1 := map[string]interface{}{
		"network_name":  "tf-test-chn-test-gray-network" + randomSuffix,
		"range_address": "192.168.178.0",
		"range_name":    "tf-test-chn-test-gray-range-updated" + randomSuffix,
		"resource_name": "tf-test-chn-test-gray" + randomSuffix,
		"random_suffix": randomSuffix,
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderBetaFactories(t),
		CheckDestroy:             testAccCheckNetworkConnectivityCustomHardwareLinkAttachmentDestroyProducer(t),
		Steps: []resource.TestStep{
			{
				Config: testAccNetworkConnectivityCustomHardwareLinkAttachment_networkConnectivityCustomHardwareLinkAttachmentBasicExample(context),
			},
			{
				ResourceName:            "google_network_connectivity_custom_hardware_link_attachment.attachment",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"labels", "location", "terraform_labels"},
			},
			{
				ResourceName:       "google_network_connectivity_custom_hardware_link_attachment.attachment",
				RefreshState:       true,
				ExpectNonEmptyPlan: true,
				ImportStateKind:    resource.ImportBlockWithResourceIdentity,
			},
			{
				Config: testAccNetworkConnectivityCustomHardwareLinkAttachment_networkConnectivityCustomHardwareLinkAttachmentBasicExample(context_1),
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction("google_network_connectivity_custom_hardware_link_attachment.attachment", plancheck.ResourceActionUpdate),
					},
				},
			},
			{
				ResourceName:            "google_network_connectivity_custom_hardware_link_attachment.attachment",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"labels", "location", "terraform_labels"},
			},
			{
				ResourceName:       "google_network_connectivity_custom_hardware_link_attachment.attachment",
				RefreshState:       true,
				ExpectNonEmptyPlan: true,
				ImportStateKind:    resource.ImportBlockWithResourceIdentity,
			},
		},
	})
}

func testAccNetworkConnectivityCustomHardwareLinkAttachment_networkConnectivityCustomHardwareLinkAttachmentBasicExample(context map[string]interface{}) string {
	return acctest.Nprintf(`
provider "google-nightly" {}

resource "google_compute_network" "network" {
  provider = google-nightly
  name = "%{network_name}"
  auto_create_subnetworks = false
}

resource "google_compute_subnetwork" "subnetwork" {
  provider = google-nightly
  name = "%{network_name}-sub"
  network = google_compute_network.network.name
  ip_cidr_range = "10.93.0.0/16"
  region = "us-south1"
}

resource "google_compute_subnetwork" "ch_subnetwork" {
  provider = google-nightly
  name = "%{network_name}-chsub"
  network = google_compute_network.network.name
  ip_cidr_range = "192.168.176.0/20"
  region = "us-south1"
  purpose = "CUSTOM_HARDWARE_LINK"
}

resource "google_compute_address" "bgp_a" {
  provider = google-nightly
  name = "%{network_name}-bgp-a"
  region = "us-south1"
  address_type = "INTERNAL"
  purpose = "SYSTEM_MANAGED"
  subnetwork = google_compute_subnetwork.subnetwork.id
}

resource "google_compute_address" "bgp_peer_a" {
  provider = google-nightly
  name = "%{network_name}-peer-a"
  region = "us-south1"
  address_type = "INTERNAL"
  purpose = "SYSTEM_MANAGED"
  subnetwork = google_compute_subnetwork.subnetwork.id
}

resource "google_compute_address" "ch_range" {
  provider = google-nightly
  name = "%{range_name}"
  region = "us-south1"
  address_type = "INTERNAL"
  purpose = "SYSTEM_MANAGED"
  subnetwork = google_compute_subnetwork.ch_subnetwork.id
  address = "%{range_address}"
}

resource "google_network_connectivity_custom_hardware_instance" "instance" {
  provider = google-nightly
  name = "%{resource_name}-inst"
  location = "us-south1"
}

resource "google_network_connectivity_custom_hardware_link_connect_pair" "pair" {
  provider = google-nightly
  name = "%{resource_name}-lcp"
  location = "us-south1-d"
  custom_hardware_instance = google_network_connectivity_custom_hardware_instance.instance.id
  link_type = "LINK_TYPE_REGULAR"
  link_speed = "LINK_SPEED100_G"
}

resource "google_network_connectivity_custom_hardware_link_attachment" "attachment" {
  provider = google-nightly
  name = "%{resource_name}"
  location = "us-south1-d"
  custom_hardware_link_connect_pair = google_network_connectivity_custom_hardware_link_connect_pair.pair.id
  subnetwork = google_compute_subnetwork.subnetwork.id
  link_type = "LINK_TYPE_REGULAR"
  bgp_ip = google_compute_address.bgp_a.id
  asn = "64512"
  peer_bgp_ip = google_compute_address.bgp_peer_a.id
  peer_asn = "64513"
  link_address_range = google_compute_address.ch_range.id
  labels = {
    env = "test"
  }
}
`, context)
}

func TestAccNetworkConnectivityCustomHardwareLinkAttachment_networkConnectivityCustomHardwareLinkAttachmentUllExample(t *testing.T) {
	t.Parallel()

	randomSuffix := acctest.RandString(t, 10)

	context := map[string]interface{}{
		"network_name":  "tf-test-chn-test-blue-network" + randomSuffix,
		"range_address": "10.168.177.0",
		"range_name":    "tf-test-chn-test-blue-range" + randomSuffix,
		"resource_name": "tf-test-chn-test-blue" + randomSuffix,
		"random_suffix": randomSuffix,
	}

	context_1 := map[string]interface{}{
		"network_name":  "tf-test-chn-test-blue-network" + randomSuffix,
		"range_address": "10.168.178.0",
		"range_name":    "tf-test-chn-test-blue-range-updated" + randomSuffix,
		"resource_name": "tf-test-chn-test-blue" + randomSuffix,
		"random_suffix": randomSuffix,
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderBetaFactories(t),
		CheckDestroy:             testAccCheckNetworkConnectivityCustomHardwareLinkAttachmentDestroyProducer(t),
		Steps: []resource.TestStep{
			{
				Config: testAccNetworkConnectivityCustomHardwareLinkAttachment_networkConnectivityCustomHardwareLinkAttachmentUllExample(context),
			},
			{
				ResourceName:            "google_network_connectivity_custom_hardware_link_attachment.attachment",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"labels", "location", "terraform_labels"},
			},
			{
				ResourceName:       "google_network_connectivity_custom_hardware_link_attachment.attachment",
				RefreshState:       true,
				ExpectNonEmptyPlan: true,
				ImportStateKind:    resource.ImportBlockWithResourceIdentity,
			},
			{
				Config: testAccNetworkConnectivityCustomHardwareLinkAttachment_networkConnectivityCustomHardwareLinkAttachmentUllExample(context_1),
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction("google_network_connectivity_custom_hardware_link_attachment.attachment", plancheck.ResourceActionUpdate),
					},
				},
			},
			{
				ResourceName:            "google_network_connectivity_custom_hardware_link_attachment.attachment",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"labels", "location", "terraform_labels"},
			},
			{
				ResourceName:       "google_network_connectivity_custom_hardware_link_attachment.attachment",
				RefreshState:       true,
				ExpectNonEmptyPlan: true,
				ImportStateKind:    resource.ImportBlockWithResourceIdentity,
			},
		},
	})
}

func testAccNetworkConnectivityCustomHardwareLinkAttachment_networkConnectivityCustomHardwareLinkAttachmentUllExample(context map[string]interface{}) string {
	return acctest.Nprintf(`
provider "google-nightly" {}

resource "google_compute_network" "network" {
  provider = google-nightly
  name = "%{network_name}"
  auto_create_subnetworks = false
}

resource "google_compute_subnetwork" "subnetwork" {
  provider = google-nightly
  name = "%{network_name}-sub"
  network = google_compute_network.network.name
  ip_cidr_range = "10.93.0.0/16"
  region = "us-south1"
}

resource "google_compute_subnetwork" "ch_subnetwork" {
  provider = google-nightly
  name = "%{network_name}-chsub"
  network = google_compute_network.network.name
  ip_cidr_range = "10.168.176.0/20"
  region = "us-south1"
  purpose = "CUSTOM_HARDWARE_LINK"
}

resource "google_compute_address" "bgp_a" {
  provider = google-nightly
  name = "%{network_name}-bgp-a"
  region = "us-south1"
  address_type = "INTERNAL"
  purpose = "SYSTEM_MANAGED"
  subnetwork = google_compute_subnetwork.subnetwork.id
}

resource "google_compute_address" "bgp_peer_a" {
  provider = google-nightly
  name = "%{network_name}-peer-a"
  region = "us-south1"
  address_type = "INTERNAL"
  purpose = "SYSTEM_MANAGED"
  subnetwork = google_compute_subnetwork.subnetwork.id
}

resource "google_compute_address" "ch_range" {
  provider = google-nightly
  name = "%{range_name}"
  region = "us-south1"
  address_type = "INTERNAL"
  purpose = "SYSTEM_MANAGED"
  subnetwork = google_compute_subnetwork.ch_subnetwork.id
  address = "%{range_address}"
}

resource "google_network_connectivity_custom_hardware_instance" "instance" {
  provider = google-nightly
  name = "%{resource_name}-inst"
  location = "us-south1"
}

resource "google_network_connectivity_custom_hardware_link_connect_pair" "pair" {
  provider = google-nightly
  name = "%{resource_name}-lcp"
  location = "us-south1-d"
  custom_hardware_instance = google_network_connectivity_custom_hardware_instance.instance.id
  link_type = "LINK_TYPE_ULL"
  link_speed = "LINK_SPEED10_G"
}

resource "google_network_connectivity_custom_hardware_link_attachment" "attachment" {
  provider = google-nightly
  name = "%{resource_name}"
  location = "us-south1-d"
  custom_hardware_link_connect_pair = google_network_connectivity_custom_hardware_link_connect_pair.pair.id
  subnetwork = google_compute_subnetwork.subnetwork.id
  link_type = "LINK_TYPE_ULL"
  bgp_ip = google_compute_address.bgp_a.id
  asn = "64512"
  peer_bgp_ip = google_compute_address.bgp_peer_a.id
  peer_asn = "64513"
  link_address_range = google_compute_address.ch_range.id
  labels = {
    env = "test"
  }
}
`, context)
}

func testAccCheckNetworkConnectivityCustomHardwareLinkAttachmentDestroyProducer(t *testing.T) func(s *terraform.State) error {
	return func(s *terraform.State) error {
		for name, rs := range s.RootModule().Resources {
			if rs.Type != "google_network_connectivity_custom_hardware_link_attachment" {
				continue
			}
			if strings.HasPrefix(name, "data.") {
				continue
			}

			config := acctest.GoogleProviderConfig(t)
			url, err := tpgresource.ReplaceVarsForTest(config, rs, transport_tpg.BaseUrl(networkconnectivity.Product, config)+"projects/{{project}}/locations/{{location}}/customHardwareLinkAttachments/{{name}}")
			if err != nil {
				return err
			}

			billingProject := ""

			if config.BillingProject != "" {
				billingProject = config.BillingProject
			}

			_, err = transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
				Config:    config,
				Method:    "GET",
				Project:   billingProject,
				RawURL:    url,
				UserAgent: config.UserAgent,
			})
			if err == nil {
				return fmt.Errorf("NetworkConnectivityCustomHardwareLinkAttachment still exists at %s", url)
			}
		}

		return nil
	}
}
